import type { KPSeed } from "./seed-types";

const STAGE = "小学" as const;
const GRADE = "四年级";
const SUBJECT = "英语";

export const g4English: KPSeed[] = [
  {
    code: "G4-EN-1-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 1 My classroom",
    title: "教室物品词汇：classroom, window, door, picture, board, light",
    sortOrder: 0,
    summary: [
      { heading: "核心词汇", body: "本单元学习与教室有关的单词：classroom（教室）、window（窗户）、door（门）、picture（图画）、board（写字板）、light（灯）。注意 light 既是“灯”也是“光”。" },
      { heading: "发音提示", body: "door 中 oor 发 /ɔː/；window 重音在第一个音节 /ˈwɪndəʊ/；picture 读 /ˈpɪktʃə/，中间的 c 发 /k/。" },
      { heading: "用法提示", body: "说“一扇窗户”要用 a window；特指教室里的那扇门用 the door。如：Open the door.（打开门。）" },
    ],
    example: {
      stem: "看图选词：教室里有一扇窗户、一扇门和一块写字板，用英语各写出一个。",
      analysis: "“窗户”是 window，“门”是 door，“写字板”是 board，注意拼写。",
      answer: "window, door, board",
    },
    prereqCodes: [],
    commonErrors: [
      { cause: "拼写错误", detail: "把 window 写成 windou，把 picture 写成 piture，漏掉字母。" },
      { cause: "大小写错误", detail: "句首单词首字母忘记大写，如 \"open the door\" 写在句首应为 \"Open the door\"。" },
    ],
    socratic: {
      keyConcepts: ["教室物品词汇", "a 与 the 的区别", "名词单数"],
      probes: ["你能说出教室里至少五样东西的英文吗？", "为什么特指那扇门时用 the door 而不是 a door？"],
      hints: ["看看你的教室，指着物品说英语。", "记单词时把词和图片对应起来记。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“窗户”用英语说是（ ）", options: ["door", "window", "board", "light"], answer: "B", hint: "想一想 window 的意思。", explanation: "window 是“窗户”，door 是“门”，board 是“写字板”，light 是“灯”。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中表示“灯”的是（ ）", options: ["light", "door", "picture", "classroom"], answer: "A", hint: "light 有“光”的意思。", explanation: "light 意为“灯；光”，其余分别是门、图画、教室。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "看图补全句子：This is my ____.（教室里有很多桌椅）", options: ["classroom", "picture", "door", "window"], answer: "A", hint: "有桌椅的地方是哪里？", explanation: "classroom 意为“教室”，符合语境。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：p_ct_re（图画）", answer: "i;u", hint: "缺少两个元音字母。", explanation: "picture 的正确拼写是 p-i-c-t-u-r-e，缺少 i 和 u。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "— What's in the classroom? — A ____ and two lights.", options: ["boards", "board", "boord", "boardes"], answer: "B", hint: "a 后面接单数名词。", explanation: "a 表示“一个”，后面用单数 board，注意拼写是 board。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "汉译英（写单词）：写字板 ____", answer: "board", hint: "b-o-a-r-d。", explanation: "“写字板”是 board，注意与 door 的拼写区分。" },
    ],
  },
  {
    code: "G4-EN-1-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 1 My classroom",
    title: "核心句型：What's in the classroom? / Let's clean the classroom.",
    sortOrder: 0,
    summary: [
      { heading: "询问教室里有什么", body: "句型 What's in the classroom?（教室里有什么？）回答用物品名称，如：A board, two lights, many desks and chairs.（一块写字板、两盏灯、许多桌椅。）" },
      { heading: "提出建议", body: "Let's + 动词原形 表示“让我们……吧”，如 Let's clean the classroom.（让我们打扫教室吧。）回答可以用 OK. / Good idea!" },
      { heading: "let me 与 let's", body: "Let me clean the board.（让我来擦写字板。）let me 是“让我（自己）做”，let's 是“让我们一起做”。" },
    ],
    example: {
      stem: "— ____ in the classroom? — A board and many desks.",
      analysis: "回答是教室里的物品，说明问句在问“教室里有什么”，用 What's in...? 句型。",
      answer: "What's",
    },
    prereqCodes: ["G4-EN-1-01"],
    commonErrors: [
      { cause: "be 动词遗漏", detail: "说成 \"What in the classroom?\"，漏掉 is（'s）。正确是 What's in the classroom?" },
      { cause: "动词形式错误", detail: "Let's 后面误用动词-ing 或 to do，如 \"Let's cleaning...\"，应接动词原形 clean。" },
    ],
    socratic: {
      keyConcepts: ["What's in...?", "Let's + 动词原形", "let me / let's 区别"],
      probes: ["What's 是哪两个词的缩写？漏掉 's 句子还对吗？", "“让我们一起打扫”和“让我来打扫”分别怎么说？区别在哪里？"],
      hints: ["What + is = What's。", "Let's 后面永远跟动词原形。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— ____ in the classroom? — A board and two lights.", options: ["What", "What's", "Where", "Where's"], answer: "B", hint: "问“有什么”不能漏掉 be 动词。", explanation: "What's = What is，询问“教室里有什么”必须用 What's in the classroom?" },
      { type: "choice", stage: "check", difficulty: 1, stem: "“让我们打扫教室吧。”英语是（ ）", options: ["Let's clean the classroom.", "Let clean the classroom.", "Let's cleaning the classroom.", "We clean classroom."], answer: "A", hint: "Let's 后接动词原形。", explanation: "Let's + 动词原形 clean，表示建议“让我们……吧”。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "— Let's clean the classroom. — ____", options: ["OK.", "Thank you.", "I'm fine.", "It's a door."], answer: "A", hint: "对建议的回应。", explanation: "别人提出建议，常用 OK. / Good idea. 回应。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全句子：Let ____ clean the board.（让我来擦写字板。）", answer: "me", hint: "“让我”是 let me。", explanation: "let me 表示“让我（自己）做”，let's 表示“让我们一起”。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列句子正确的是（ ）", options: ["What's in the classroom?", "What in the classroom?", "What's on the classroom?", "What are in classroom?"], answer: "A", hint: "必须有 be 动词，介词用 in。", explanation: "正确句型是 What's in the classroom?“在教室里”用 in。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "汉译英：让我们擦窗户吧。____ clean the window.", answer: "let's", hint: "“让我们”三个字对应一个词。", explanation: "Let's（= Let us）+ 动词原形 clean，句首大写，答案小写规范为 let's。" },
    ],
  },
  {
    code: "G4-EN-1-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 1 My classroom",
    title: "语音：字母组合 a-e 发 /eɪ/（cake, face, name）",
    sortOrder: 0,
    summary: [
      { heading: "a-e 结构", body: "“元音字母 a + 辅音字母 + 不发音的 e”结构中，a 发字母本身的音 /eɪ/，结尾的 e 不发音。如：cake（蛋糕）、face（脸）、name（名字）、make（制作）。" },
      { heading: "对比记忆", body: "没有结尾 e 时 a 常发 /æ/，如 cap（帽子）、map（地图）；加上 e 变成 cape、made 时 a 发 /eɪ/。对比：cap—cape, mad—made。" },
      { heading: "拼读方法", body: "看到 a-e 结构就读 /eɪ/：c-a-k-e → /keɪk/，n-a-m-e → /neɪm/。结尾的 e 只做“提示”，自己不出声。" },
    ],
    example: {
      stem: "判断下列单词中 a 的发音是否与 cake 相同：name, cap, face。",
      analysis: "cake、name、face 都是 a-e 结构，a 发 /eɪ/；cap 没有结尾 e，a 发 /æ/。",
      answer: "name 和 face 与 cake 相同（/eɪ/），cap 不同（/æ/）。",
    },
    prereqCodes: ["G4-EN-1-02"],
    commonErrors: [
      { cause: "发音混淆", detail: "把 cake 读成 /kæk/，忽略结尾 e 的作用；结尾的 e 不发音但会让前面的 a 读字母音。" },
      { cause: "拼写漏字母", detail: "把 name 写成 nam、make 写成 mak，漏掉不发音的 e。" },
    ],
    socratic: {
      keyConcepts: ["a-e 结构", "/eɪ/ 发音", "不发音的 e", "与 /æ/ 对比"],
      probes: ["cap 和 cape 发音有什么不同？是谁改变了发音？", "a-e 结构中结尾的 e 发音吗？它起什么作用？"],
      hints: ["读一读 cake、face、name，听听 a 发什么音。", "对比 cap 和 cape，感受 /æ/ 和 /eɪ/ 的区别。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中 a 发 /eɪ/ 的是（ ）", options: ["cap", "cake", "bag", "map"], answer: "B", hint: "找 a-e 结构的单词。", explanation: "cake 是 a-e 结构，a 发 /eɪ/；其余 a 发 /æ/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "cake 结尾的字母 e（ ）", options: ["发 /e/", "发 /iː/", "不发音", "发 /eɪ/"], answer: "C", hint: "a-e 结构中 e 的作用是什么？", explanation: "a-e 结构中结尾 e 不发音，只提示 a 读字母音 /eɪ/。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "与 name 中 a 发音相同的单词是（ ）", options: ["face", "cat", "map", "dad"], answer: "A", hint: "name 的 a 发 /eɪ/。", explanation: "face 也是 a-e 结构，a 发 /eɪ/；cat、map、dad 中 a 发 /æ/。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：m_k_（制作），使 a 发 /eɪ/", answer: "a;e", hint: "a-e 结构。", explanation: "make 中 a 发 /eɪ/，结尾 e 不发音。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词中 a 的发音相同？（ ）", options: ["cake, name, face", "cake, cap, face", "name, map, bag", "face, cat, dad"], answer: "A", hint: "三个都是 a-e 结构吗？", explanation: "cake、name、face 都是 a-e 结构，a 都发 /eɪ/。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "cap 变成 cape 后，字母 a 的发音（ ）", options: ["不变", "由 /æ/ 变为 /eɪ/", "由 /eɪ/ 变为 /æ/", "不发音"], answer: "B", hint: "加上结尾 e 会发生什么？", explanation: "cap 中 a 发 /æ/，加 e 成 cape 后 a-e 结构使 a 发 /eɪ/。" },
    ],
  },
  {
    code: "G4-EN-2-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 2 My schoolbag",
    title: "学习用品词汇：schoolbag, book, pencil box, ruler, eraser, crayon",
    sortOrder: 0,
    summary: [
      { heading: "核心词汇", body: "本单元学习用品词汇：schoolbag（书包）、book（书）、pencil box（铅笔盒）、ruler（尺子）、eraser（橡皮）、crayon（蜡笔）。还有各种书：Chinese book（语文书）、English book（英语书）、maths book（数学书）、storybook（故事书）。" },
      { heading: "a 与 an", body: "eraser 以元音音素开头，前面用 an：an eraser（一块橡皮）；其余用 a：a ruler, a book, a schoolbag。" },
      { heading: "发音提示", body: "schoolbag 读 /ˈskuːlbæɡ/；eraser 读 /ɪˈreɪzə/，重音在第二个音节；crayon 读 /ˈkreɪən/。" },
    ],
    example: {
      stem: "选择：I have ____ eraser and ____ ruler.（a / an）",
      analysis: "eraser 以元音音素 /ɪ/ 开头，用 an；ruler 以辅音音素 /r/ 开头，用 a。",
      answer: "an eraser and a ruler",
    },
    prereqCodes: ["G4-EN-1-01"],
    commonErrors: [
      { cause: "a/an 误用", detail: "写成 \"a eraser\"，记住 eraser 前必须用 an。" },
      { cause: "拼写错误", detail: "把 eraser 写成 \"erasar\"，schoolbag 拆写成 \"school bag\"（作一个词时连写）。" },
    ],
    socratic: {
      keyConcepts: ["学习用品词汇", "a 与 an 的用法", "元音音素开头"],
      probes: ["为什么 an eraser 用 an 而 a ruler 用 a？", "你的书包里有什么？能用英语说出三样吗？"],
      hints: ["看单词的第一个发音：元音音素开头用 an。", "打开书包，边指边说英语单词。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“书包”用英语说是（ ）", options: ["schoolbag", "pencil box", "storybook", "crayon"], answer: "A", hint: "school + bag。", explanation: "schoolbag 意为“书包”，由 school（学校）+ bag（包）组成。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "I have ____ eraser.", options: ["a", "an", "two", "/"], answer: "B", hint: "eraser 以元音音素开头。", explanation: "eraser 以元音音素 /ɪ/ 开头，前面用 an。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "下列不属于学习用品的是（ ）", options: ["ruler", "crayon", "door", "pencil box"], answer: "C", hint: "door 是什么？", explanation: "door 是“门”，属于教室设施，其余都是学习用品。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写单词）：蜡笔 ____", answer: "crayon", hint: "c-r-a-y-o-n。", explanation: "“蜡笔”是 crayon，注意中间是 a-y。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "— What's in your schoolbag? — An English book, a Chinese book and two ____.（故事书）", options: ["storybook", "storybooks", "story book", "storysbook"], answer: "B", hint: "two 后面用复数。", explanation: "two 后接复数 storybooks，storybook 是连写的一个词。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "用 a 或 an 填空：____ English book", answer: "an", hint: "English 以什么音开头？", explanation: "English 以元音音素 /ɪ/ 开头，用 an。" },
    ],
  },
  {
    code: "G4-EN-2-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 2 My schoolbag",
    title: "核心句型：What's in your schoolbag? / What colour is it?",
    sortOrder: 0,
    summary: [
      { heading: "询问书包里有什么", body: "What's in your schoolbag?（你的书包里有什么？）回答：An English book, a maths book and three storybooks.（一本英语书、一本数学书和三本故事书。）" },
      { heading: "询问颜色", body: "What colour is it?（它是什么颜色的？）回答：It's blue and white.（它是蓝白相间的。）colour 也可写作 color（美式）。" },
      { heading: "感谢与应答", body: "得到帮助时说 Thank you so much!（太感谢了！）回应可以说 You're welcome." },
    ],
    example: {
      stem: "— What colour is your schoolbag? — ____ （它是黑色的。）",
      analysis: "问颜色，用 It's + 颜色 回答，“黑色的”是 black。",
      answer: "It's black.",
    },
    prereqCodes: ["G4-EN-2-01"],
    commonErrors: [
      { cause: "be 动词遗漏", detail: "回答颜色时说 \"It blue.\"，漏掉 is，应为 It's blue." },
      { cause: "单复数错误", detail: "three storybook 忘记加 s，应为 three storybooks。" },
    ],
    socratic: {
      keyConcepts: ["What's in your...?", "What colour is it?", "It's + 颜色"],
      probes: ["What colour is it? 和 What's in it? 分别问什么？", "回答颜色时为什么要有 It's？只写 blue 行不行？"],
      hints: ["It is = It's，句子里要有 be 动词。", "数字大于一，名词要变复数。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— What's in your schoolbag? — ____", options: ["It's blue.", "An English book and two pencils.", "Thank you.", "It's on the desk."], answer: "B", hint: "问的是“书包里有什么”。", explanation: "回答书包里的物品：一本英语书和两支铅笔。A 回答的是颜色。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "“它是什么颜色的？”英语是（ ）", options: ["What's it?", "What colour is it?", "What is colour?", "Where is it?"], answer: "B", hint: "colour = 颜色。", explanation: "What colour is it? 用于询问颜色。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— What colour is your bag? — ____", options: ["It's red.", "It's a bag.", "Three books.", "OK."], answer: "A", hint: "用 It's + 颜色回答。", explanation: "询问颜色用 It's + 颜色词回答，red（红色）。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全句子：What ____ is it? — It's yellow.", answer: "colour|color", hint: "问颜色的句型。", explanation: "What colour is it? 询问颜色，colour 为英式拼写，color 为美式。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列回答对应 What's in your schoolbag? 且语法正确的是（ ）", options: ["A English book and a maths book.", "An English book and a maths book.", "An English book and an maths book.", "English book and maths book."], answer: "B", hint: "注意 a 和 an。", explanation: "English 元音音素开头用 an，maths 辅音音素开头用 a，可数名词单数前不能没有冠词。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "补全对话：— ____ in your schoolbag? — A Chinese book and three storybooks.", answer: "what's", hint: "问“有什么”的句型。", explanation: "What's in your schoolbag? 询问书包里有什么，what's = what is。" },
    ],
  },
  {
    code: "G4-EN-2-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 2 My schoolbag",
    title: "语音：字母组合 i-e 发 /aɪ/（like, kite, five）",
    sortOrder: 0,
    summary: [
      { heading: "i-e 结构", body: "“i + 辅音 + 不发音 e”结构中，i 发字母音 /aɪ/。如：like（喜欢）、kite（风筝）、five（五）、nice（美好的）、rice（米饭）。" },
      { heading: "对比记忆", body: "没有结尾 e 时 i 常发 /ɪ/，如 sit（坐）、big（大的）；加 e 后 i 发 /aɪ/：bit—bite, kit—kite。" },
      { heading: "拼读练习", body: "k-i-t-e → /kaɪt/，f-i-v-e → /faɪv/。记单词时把发音和拼写对应：/aɪ/ 常对应 i-e。" },
    ],
    example: {
      stem: "找出与 like 中 i 发音不同的单词：five, big, kite。",
      analysis: "like、five、kite 都是 i-e 结构，i 发 /aɪ/；big 中 i 发 /ɪ/。",
      answer: "big（i 发 /ɪ/，其余发 /aɪ/）。",
    },
    prereqCodes: ["G4-EN-2-02"],
    commonErrors: [
      { cause: "发音混淆", detail: "把 kite 读成 /kɪt/，忽略结尾 e 让 i 读 /aɪ/。" },
      { cause: "拼写漏 e", detail: "把 five 写成 \"fiv\"，like 写成 \"lik\"，漏掉不发音的 e。" },
    ],
    socratic: {
      keyConcepts: ["i-e 结构", "/aɪ/ 发音", "与 /ɪ/ 对比"],
      probes: ["kit 和 kite 发音差在哪里？", "你能再举出两个 i-e 结构的单词吗？"],
      hints: ["读一读 five 和 big，感受 i 发音的不同。", "看到“i + 辅音 + e”就读 /aɪ/。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中 i 发 /aɪ/ 的是（ ）", options: ["big", "kite", "sit", "six"], answer: "B", hint: "找 i-e 结构。", explanation: "kite 是 i-e 结构，i 发 /aɪ/；其余 i 发 /ɪ/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "five 结尾的 e（ ）", options: ["发 /e/", "不发音", "发 /iː/", "发 /aɪ/"], answer: "B", hint: "和 cake 中的 e 一样吗？", explanation: "i-e 结构中结尾 e 不发音，只提示 i 读字母音。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "与 nice 中 i 发音相同的是（ ）", options: ["rice", "big", "fish", "milk"], answer: "A", hint: "nice 的 i 发 /aɪ/。", explanation: "rice 是 i-e 结构，i 发 /aɪ/，与 nice 相同。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：k_t_（风筝）", answer: "i;e", hint: "i-e 结构。", explanation: "kite 的拼写是 k-i-t-e，i 发 /aɪ/，结尾 e 不发音。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词 i 的发音都相同？（ ）", options: ["like, five, rice", "like, big, five", "kite, sit, nice", "five, fish, milk"], answer: "A", hint: "都是 i-e 结构吗？", explanation: "like、five、rice 都是 i-e 结构，i 都发 /aɪ/。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "bit 加上结尾 e 变成 bite 后，字母 i 的发音（ ）", options: ["不变", "由 /ɪ/ 变为 /aɪ/", "由 /aɪ/ 变为 /ɪ/", "不发音"], answer: "B", hint: "结尾 e 的作用。", explanation: "bit 中 i 发 /ɪ/，bite 是 i-e 结构，i 发 /aɪ/。" },
    ],
  },
  {
    code: "G4-EN-3-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 3 My friends",
    title: "描述人物的词汇：tall, short, strong, thin, friendly, quiet",
    sortOrder: 0,
    summary: [
      { heading: "外貌词汇", body: "tall（高的）、short（矮的；短的）、strong（强壮的）、thin（瘦的）用来描述身材。如：He is tall and strong.（他又高又壮。）" },
      { heading: "性格词汇", body: "friendly（友好的）、quiet（安静的）、cute（可爱的）用来描述性格。如：She is quiet and friendly.（她安静又友好。）" },
      { heading: "hair 与 shoe", body: "She has long hair.（她有一头长发。）Her shoes are black.（她的鞋子是黑色的。）hair 通常作不可数名词；鞋子成双，常用复数 shoes。" },
    ],
    example: {
      stem: "用英语描述你的同桌：他又高又壮，而且很友好。",
      analysis: "“又高又壮”是 tall and strong，“友好”是 friendly，用 He is... 句型。",
      answer: "He is tall and strong. He is friendly.",
    },
    prereqCodes: ["G4-EN-2-01"],
    commonErrors: [
      { cause: "be 动词遗漏", detail: "说 \"He tall and strong.\"，形容词前必须有 be 动词：He is tall and strong." },
      { cause: "he/she 混淆", detail: "男生用 he，女生用 she，介绍朋友时容易混用；对应的物主代词是 his（他的）和 her（她的）。" },
    ],
    socratic: {
      keyConcepts: ["外貌形容词", "性格形容词", "He is... / She is...", "his / her"],
      probes: ["描述人时，英语里形容词前为什么要加 is？", "tall 和 short 是一对什么词？你能举出它们描述的对象吗？"],
      hints: ["He/She + is + 形容词。", "想想反义词：tall—short, strong—thin。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“友好的”用英语说是（ ）", options: ["quiet", "friendly", "strong", "thin"], answer: "B", hint: "friend + ly。", explanation: "friendly 意为“友好的”，由 friend（朋友）加 -ly 构成。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "He ____ tall and strong.", options: ["is", "are", "am", "has"], answer: "A", hint: "he 是第三人称单数。", explanation: "he 搭配 be 动词 is；描述外貌用 be 动词，不用 has。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "She has long ____.（她有一头长发。）", options: ["hairs", "hair", "haire", "hair's"], answer: "B", hint: "hair 是不可数名词。", explanation: "hair 通常作不可数名词，不加 s：long hair。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写单词）：强壮的 ____", answer: "strong", hint: "s-t-r-o-n-g。", explanation: "“强壮的”是 strong，反义词是 thin（瘦的）。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列描述正确的是（ ）", options: ["She is quiet and friendly.", "She quiet and friendly.", "Her is quiet and friendly.", "She are quiet and friendly."], answer: "A", hint: "主语 + is + 形容词。", explanation: "she 作主语，be 动词用 is：She is quiet and friendly. her 不能作主语。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— What's her name? — ____ name is Amy.", options: ["His", "Her", "She", "He's"], answer: "B", hint: "her name 对应 her。", explanation: "问句用 her name（女生），回答也用 Her name is...；his 是“他的”。" },
    ],
  },
  {
    code: "G4-EN-3-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 3 My friends",
    title: "核心句型：What's his/her name? / He has...",
    sortOrder: 0,
    summary: [
      { heading: "询问姓名", body: "What's his name?（他叫什么名字？）— His name is Zhang Peng. / What's her name?（她叫什么名字？）— Her name is Amy. 男生用 his，女生用 her。" },
      { heading: "描述特征", body: "He has glasses and his shoes are blue.（他戴眼镜，他的鞋子是蓝色的。）“有、戴”用 have/has，he/she 后用 has。" },
      { heading: "介绍朋友", body: "This is my friend. He is tall and thin. He is very friendly. 先介绍是谁，再描述外貌和性格，是介绍朋友的常用顺序。" },
    ],
    example: {
      stem: "— What's ____ name? — Her name is Chen Jie.",
      analysis: "回答用了 Her name，说明是女生，问句也要用 her。",
      answer: "her",
    },
    prereqCodes: ["G4-EN-3-01"],
    commonErrors: [
      { cause: "his/her 混淆", detail: "女生名字用 his name 提问，记住男生 his、女生 her，问与答要一致。" },
      { cause: "has/have 误用", detail: "He have glasses. 错误，第三人称单数 he/she 后用 has：He has glasses." },
    ],
    socratic: {
      keyConcepts: ["What's his/her name?", "have/has", "his 与 her 对应性别"],
      probes: ["什么时候用 his，什么时候用 her？", "为什么 He has 不能用 He have？"],
      hints: ["看他的性别：男 his，女 her。", "he/she/it 后面的“有”要用 has。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— What's ____ name? — His name is John.", options: ["her", "his", "he", "she"], answer: "B", hint: "回答是 His name。", explanation: "回答用 his（男生），问句也用 his name。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "She ____ long hair and big eyes.", options: ["have", "has", "is", "are"], answer: "B", hint: "she 是第三人称单数。", explanation: "“有”用 have，第三人称单数 she 后变为 has。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— What's her name? — ____", options: ["His name is Amy.", "Her name is Amy.", "She name is Amy.", "Her names is Amy."], answer: "B", hint: "女生用 her。", explanation: "her name 提问，her name 回答：Her name is Amy." },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全句子：He ____ glasses.（他戴眼镜。）", answer: "has", hint: "he 后面的“有”。", explanation: "he 是第三人称单数，have 要变成 has。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列句子正确的是（ ）", options: ["He have a blue bag.", "He has a blue bag.", "He is have a blue bag.", "He haves a blue bag."], answer: "B", hint: "he 后面 have 怎么变？", explanation: "第三人称单数用 has：He has a blue bag." },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— ____ — His name is Wu Binbin.（选择合适的问句）", options: ["What's her name?", "What's his name?", "What's your name?", "Who's she?"], answer: "B", hint: "回答是 His name。", explanation: "回答 His name is... 对应问句 What's his name?" },
    ],
  },
  {
    code: "G4-EN-3-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 3 My friends",
    title: "语音：字母组合 o-e 发 /əʊ/（nose, note, Coke）",
    sortOrder: 0,
    summary: [
      { heading: "o-e 结构", body: "“o + 辅音 + 不发音 e”结构中，o 发字母音 /əʊ/。如：nose（鼻子）、note（便条）、Coke（可乐）、home（家）、hope（希望）。" },
      { heading: "对比记忆", body: "没有结尾 e 时 o 常发 /ɒ/，如 not（不）、box（盒子）、dog（狗）；加 e 后 o 发 /əʊ/：not—note, hop—hope。" },
      { heading: "拼读练习", body: "n-o-t-e → /nəʊt/，h-o-p-e → /həʊp/。发 /əʊ/ 时口型从开到合，像中文“欧”。" },
    ],
    example: {
      stem: "判断 note 和 not 中 o 的发音是否相同。",
      analysis: "note 是 o-e 结构，o 发 /əʊ/；not 没有结尾 e，o 发 /ɒ/。",
      answer: "不同。note 中 o 发 /əʊ/，not 中 o 发 /ɒ/。",
    },
    prereqCodes: ["G4-EN-3-02"],
    commonErrors: [
      { cause: "发音混淆", detail: "把 note 读成 /nɒt/，忽略结尾 e 的作用。" },
      { cause: "拼写漏 e", detail: "把 home 写成 \"hom\"，nose 写成 \"nos\"，漏掉不发音的 e。" },
    ],
    socratic: {
      keyConcepts: ["o-e 结构", "/əʊ/ 发音", "与 /ɒ/ 对比"],
      probes: ["not 和 note 只差一个字母 e，发音差在哪里？", "home 中哪个字母不发音？"],
      hints: ["o + 辅音 + e 就读 /əʊ/。", "读一读 nose、home，听听共同的音。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中 o 发 /əʊ/ 的是（ ）", options: ["dog", "nose", "box", "not"], answer: "B", hint: "找 o-e 结构。", explanation: "nose 是 o-e 结构，o 发 /əʊ/；dog、box、not 中 o 发 /ɒ/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "home 中不发音的字母是（ ）", options: ["h", "o", "m", "e"], answer: "D", hint: "o-e 结构的特点。", explanation: "o-e 结构中结尾 e 不发音，o 发 /əʊ/。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "与 note 中 o 发音相同的是（ ）", options: ["hope", "not", "box", "dog"], answer: "A", hint: "note 的 o 发 /əʊ/。", explanation: "hope 是 o-e 结构，o 发 /əʊ/，与 note 相同。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：h_m_（家），使 o 发 /əʊ/", answer: "o;e", hint: "o-e 结构。", explanation: "home 的拼写是 h-o-m-e，o 发 /əʊ/，结尾 e 不发音。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词 o 的发音都相同？（ ）", options: ["nose, note, home", "nose, dog, home", "note, box, not", "Coke, not, nose"], answer: "A", hint: "都是 o-e 结构吗？", explanation: "nose、note、home 都是 o-e 结构，o 都发 /əʊ/。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "hop 加结尾 e 变成 hope 后，o 的发音（ ）", options: ["不变", "由 /ɒ/ 变为 /əʊ/", "由 /əʊ/ 变为 /ɒ/", "不发音"], answer: "B", hint: "结尾 e 改变了元音。", explanation: "hop 中 o 发 /ɒ/，hope 是 o-e 结构，o 发 /əʊ/。" },
    ],
  },
  {
    code: "G4-EN-4-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 4 My home",
    title: "房间与家具词汇：bedroom, living room, kitchen, bathroom, study",
    sortOrder: 0,
    summary: [
      { heading: "房间词汇", body: "bedroom（卧室）、living room（客厅）、kitchen（厨房）、bathroom（浴室；卫生间）、study（书房）。如：This is my bedroom.（这是我的卧室。）" },
      { heading: "家具词汇", body: "bed（床）、sofa（沙发）、phone（电话）、table（桌子）、fridge（冰箱）。fridge 是 refrigerator 的口语形式。" },
      { heading: "发音提示", body: "kitchen 读 /ˈkɪtʃɪn/，tch 发 /tʃ/；bathroom 中 th 发 /θ/，要咬舌尖；study 中 u 发 /ʌ/。" },
    ],
    example: {
      stem: "连一连：做饭的地方、睡觉的地方、看书学习的地方分别是什么房间？",
      analysis: "做饭在 kitchen（厨房），睡觉在 bedroom（卧室），学习在 study（书房）。",
      answer: "kitchen, bedroom, study",
    },
    prereqCodes: ["G4-EN-3-01"],
    commonErrors: [
      { cause: "拼写错误", detail: "把 kitchen 写成 \"kichten\"，bathroom 漏写 h 或 a。" },
      { cause: "词义混淆", detail: "study 作名词是“书房”，作动词是“学习”，容易混淆；bedroom 和 bathroom 也只差一个字母。" },
    ],
    socratic: {
      keyConcepts: ["房间词汇", "家具词汇", "词与功能对应"],
      probes: ["你家有哪些房间？能用英语说出三个吗？", "bedroom 和 bathroom 拼写差在哪里？意思差在哪里？"],
      hints: ["bed（床）+ room（房间）= bedroom。", "bath（洗澡）+ room = bathroom。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“客厅”用英语说是（ ）", options: ["bedroom", "living room", "kitchen", "study"], answer: "B", hint: "living 表示“生活的”。", explanation: "living room 意为“客厅”，是家人起居活动的房间。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "做饭的房间是（ ）", options: ["bathroom", "bedroom", "kitchen", "study"], answer: "C", hint: "cook 和 kitchen 是一家。", explanation: "kitchen 是“厨房”，是做饭的地方。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "下列属于家具的是（ ）", options: ["sofa", "kitchen", "study", "bathroom"], answer: "A", hint: "房间还是家具？", explanation: "sofa 是“沙发”，属于家具；其余是房间。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写单词）：冰箱 ____", answer: "fridge", hint: "f-r-i-d-g-e。", explanation: "“冰箱”口语说 fridge，完整形式是 refrigerator。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "— Where is your father? — He is in the ____. He is reading books.", options: ["kitchen", "study", "bathroom", "bedroom"], answer: "B", hint: "看书的地方。", explanation: "看书学习在 study（书房）。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "拼写填空：b_droom（卧室）", answer: "e", hint: "bed + room。", explanation: "bedroom 由 bed + room 组成，注意与 bathroom 区分。" },
    ],
  },
  {
    code: "G4-EN-4-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 4 My home",
    title: "核心句型：Where is she? / Is she in the study? / Are they...?",
    sortOrder: 0,
    summary: [
      { heading: "询问单个人在哪里", body: "Where is she?（她在哪里？）— She's in the study.（她在书房。）猜测用一般疑问句：Is she in the living room? — Yes, she is. / No, she isn't." },
      { heading: "询问复数物品在哪里", body: "Where are the keys?（钥匙在哪里？）— They're on the table.（它们在桌子上。）Are they on the table? — Yes, they are. / No, they aren't." },
      { heading: "单复数要一致", body: "单数用 is/Is it...?，复数用 are/Are they...?。回答也要一致：Is it...? — Yes, it is.；Are they...? — No, they aren't." },
    ],
    example: {
      stem: "— Are the keys on the fridge? — No, ____.（不，不在。）",
      analysis: "keys 是复数，用 they 指代，否定回答是 No, they aren't. ",
      answer: "they aren't",
    },
    prereqCodes: ["G4-EN-4-01"],
    commonErrors: [
      { cause: "is/are 混用", detail: "复数主语用 is：The keys is... 错误，应为 The keys are..." },
      { cause: "回答不一致", detail: "Are they...? 却回答 Yes, it is. 人称和单复数要保持一致。" },
    ],
    socratic: {
      keyConcepts: ["Where is/are...?", "Is she...? 的回答", "Are they...? 的回答", "单复数一致"],
      probes: ["什么时候用 Where is，什么时候用 Where are？", "Are they...? 的肯定和否定回答分别是什么？"],
      hints: ["一个用 is，多个用 are。", "怎么问就怎么答：问 Are they，答 they are/aren't。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— Is she in the kitchen? — ____, she is.（肯定回答）", options: ["Yes", "No", "Not", "She"], answer: "A", hint: "肯定回答用 Yes。", explanation: "Is she...? 的肯定回答是 Yes, she is.；否定是 No, she isn't." },
      { type: "choice", stage: "check", difficulty: 1, stem: "Where ____ the keys?", options: ["is", "are", "am", "be"], answer: "B", hint: "keys 是复数。", explanation: "keys 是复数，be 动词用 are：Where are the keys?" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— Are they on the table? — No, ____. ", options: ["they are", "it isn't", "they aren't", "they not"], answer: "C", hint: "复数否定回答。", explanation: "Are they...? 的否定回答是 No, they aren't." },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全句子：____ is she? — She's in the study.", answer: "where", hint: "问地点的词。", explanation: "询问地点用 Where：Where is she?（她在哪里？）" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列对话正确的是（ ）", options: ["— Is she in the study? — Yes, she is.", "— Is she in the study? — Yes, she are.", "— Is she in the study? — Yes, it is.", "— Is she in the study? — Yes, she isn't."], answer: "A", hint: "人称和 be 动词要一致。", explanation: "Is she...? 的肯定回答只能是 Yes, she is." },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— Where are the keys? — ____ on the fridge.", options: ["It's", "They're", "She's", "He's"], answer: "B", hint: "keys 是复数。", explanation: "复数 keys 用 they 指代：They're on the fridge." },
    ],
  },
  {
    code: "G4-EN-4-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 4 My home",
    title: "语音：字母组合 u-e 发 /juː/（use, cute, excuse）",
    sortOrder: 0,
    summary: [
      { heading: "u-e 结构", body: "“u + 辅音 + 不发音 e”结构中，u 常发 /juː/。如：use（使用）、cute（可爱的）、excuse（原谅；excuse me 打扰一下）。" },
      { heading: "对比记忆", body: "没有结尾 e 时 u 常发 /ʌ/，如 bus（公共汽车）、duck（鸭子）、up（向上）；u-e 结构中 u 发 /juː/：cute, use。" },
      { heading: "发音提示", body: "/juː/ 像中文“油”的音。use 作动词“使用”读 /juːz/，结尾 s 浊化。" },
    ],
    example: {
      stem: "找出与 cute 中 u 发音相同的单词：bus, use, duck。",
      analysis: "cute、use 是 u-e 结构，u 发 /juː/；bus、duck 中 u 发 /ʌ/。",
      answer: "use",
    },
    prereqCodes: ["G4-EN-4-02"],
    commonErrors: [
      { cause: "发音混淆", detail: "把 cute 读成 /kʌt/，忽略结尾 e 让 u 读 /juː/。" },
      { cause: "拼写漏 e", detail: "把 use 写成 \"us\"，us（我们）和 use（使用）是两个不同的词。" },
    ],
    socratic: {
      keyConcepts: ["u-e 结构", "/juː/ 发音", "us 与 use 区分"],
      probes: ["us 和 use 发音一样吗？意思一样吗？", "你能找出本单元里 u-e 结构的单词吗？"],
      hints: ["u + 辅音 + e 读 /juː/，像“油”。", "读 bus 和 use，对比 u 的发音。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中 u 发 /juː/ 的是（ ）", options: ["bus", "cute", "duck", "up"], answer: "B", hint: "找 u-e 结构。", explanation: "cute 是 u-e 结构，u 发 /juː/；bus、duck、up 中 u 发 /ʌ/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "use 结尾的 e（ ）", options: ["发 /e/", "不发音", "发 /iː/", "发 /juː/"], answer: "B", hint: "和前面学的规律一样。", explanation: "u-e 结构中结尾 e 不发音，u 发 /juː/。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "与 excuse 中 u 发音相同的是（ ）", options: ["use", "bus", "duck", "mum"], answer: "A", hint: "excuse 的 u 发 /juː/。", explanation: "use 是 u-e 结构，u 发 /juː/，与 excuse 相同。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：c_t_（可爱的）", answer: "u;e", hint: "u-e 结构。", explanation: "cute 的拼写是 c-u-t-e，u 发 /juː/。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词 u 的发音都相同？（ ）", options: ["use, cute, excuse", "use, bus, cute", "cute, duck, up", "excuse, mum, use"], answer: "A", hint: "都是 u-e 结构吗？", explanation: "use、cute、excuse 都是 u-e 结构，u 都发 /juː/。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "“打扰一下”英语常说（ ）", options: ["Excuse me.", "Use me.", "Cute me.", "Sorry me."], answer: "A", hint: "excuse 有“原谅”的意思。", explanation: "Excuse me. 是礼貌用语“打扰一下”，excuse 是 u-e 结构单词。" },
    ],
  },
  {
    code: "G4-EN-5-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 5 Dinner's ready",
    title: "食物与餐具词汇：beef, chicken, noodles, soup, vegetable, chopsticks",
    sortOrder: 0,
    summary: [
      { heading: "食物词汇", body: "beef（牛肉）、chicken（鸡肉）、noodles（面条，常用复数）、soup（汤）、vegetable（蔬菜）、rice（米饭）。如：I'd like some noodles.（我想要一些面条。）" },
      { heading: "餐具词汇", body: "chopsticks（筷子，常用复数）、bowl（碗）、fork（叉子）、knife（刀）、spoon（勺子）。Pass me the knife and fork.（把刀叉递给我。）" },
      { heading: "可数与不可数", body: "beef、chicken（鸡肉）、soup、rice 通常不可数，前面用 some；noodles、vegetables、chopsticks 常用复数形式。" },
    ],
    example: {
      stem: "选择：I'd like some ____（牛肉）and ____（面条）.",
      analysis: "beef 不可数，直接用 beef；noodles 常用复数形式。",
      answer: "beef; noodles",
    },
    prereqCodes: ["G4-EN-4-01"],
    commonErrors: [
      { cause: "单复数错误", detail: "写成 two beefs 或 a soup，beef、soup 不可数，不能直接加 s 或用 a。" },
      { cause: "拼写错误", detail: "chopsticks 漏写 h 或 s；vegetable 写成 \"vegtable\"，漏掉 e。" },
    ],
    socratic: {
      keyConcepts: ["食物词汇", "餐具词汇", "可数与不可数", "some 的用法"],
      probes: ["beef 为什么不能加 s？noodles 为什么常加 s？", "你能说出三种中国食物的英语吗？"],
      hints: ["不可数名词用 some，不加 s。", "筷子是两根，所以 chopsticks 带 s。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“面条”用英语说是（ ）", options: ["rice", "noodles", "soup", "beef"], answer: "B", hint: "常用复数形式。", explanation: "noodles 意为“面条”，常用复数。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "吃饭用的“筷子”是（ ）", options: ["fork", "knife", "chopsticks", "spoon"], answer: "C", hint: "中国人吃饭用什么？", explanation: "chopsticks 是“筷子”；fork 叉子，knife 刀，spoon 勺子。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "I'd like some ____.（我想要一些牛肉。）", options: ["beefs", "beef", "a beef", "beeves"], answer: "B", hint: "beef 不可数。", explanation: "beef 是不可数名词，some 后直接用 beef，不加 s。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写单词）：汤 ____", answer: "soup", hint: "s-o-u-p。", explanation: "“汤”是 soup，不可数名词。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列句子正确的是（ ）", options: ["I'd like some noodles.", "I'd like some noodle's.", "I'd like a noodles.", "I'd like some rices."], answer: "A", hint: "注意单复数和不可数名词。", explanation: "noodles 复数可用 some 修饰；rice 不可数不能加 s。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— Would you like a knife and fork? — No, thanks. I can use ____.（我会用筷子。）", options: ["chopstick", "chopsticks", "a chopsticks", "chopsticke"], answer: "B", hint: "筷子常用复数。", explanation: "筷子是成对的，用复数 chopsticks。" },
    ],
  },
  {
    code: "G4-EN-5-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 5 Dinner's ready",
    title: "核心句型：What's for dinner? / What would you like?",
    sortOrder: 0,
    summary: [
      { heading: "询问吃什么", body: "What's for dinner?（晚饭吃什么？）回答直接说食物：Some fish and rice.（一些鱼和米饭。）" },
      { heading: "表达想要什么", body: "What would you like?（你想要什么？）— I'd like some soup and bread, please.（我想要一些汤和面包。）I'd like = I would like（我想要）。" },
      { heading: "餐桌用语", body: "Dinner's ready!（晚饭好了！）Help yourself.（随便吃/请自便。）Would you like...? 的回答：Yes, please. / No, thanks." },
    ],
    example: {
      stem: "— What would you like? — ____ some beef and vegetables.",
      analysis: "“我想要”用 I'd like，是 I would like 的缩写。",
      answer: "I'd like",
    },
    prereqCodes: ["G4-EN-5-01"],
    commonErrors: [
      { cause: "缩写误写", detail: "把 I'd like 写成 \"I'd like to\" 后接名词，或写成 \"I would likes\"，would 后接动词原形。" },
      { cause: "答非所问", detail: "What would you like? 回答 Yes/No 错误，这是特殊疑问句，要回答具体食物。" },
    ],
    socratic: {
      keyConcepts: ["What would you like?", "I'd like...", "Would you like...? 的回答"],
      probes: ["What would you like? 能回答 Yes 吗？为什么？", "Would you like some soup? 想喝和不想喝分别怎么回答？"],
      hints: ["I'd like = I would like，后面直接接想要的食物。", "Would you like...? 才用 Yes, please. / No, thanks. 回答。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— What would you like? — ____", options: ["Yes, please.", "I'd like some rice.", "No, thanks.", "It's delicious."], answer: "B", hint: "问想要什么食物。", explanation: "What would you like? 用 I'd like + 食物回答；Yes/No 回答用于 Would you like...?" },
      { type: "choice", stage: "check", difficulty: 1, stem: "— Would you like some soup? — Yes, ____.（肯定回答）", options: ["thanks", "please", "I would", "I like"], answer: "B", hint: "礼貌的肯定回答。", explanation: "Would you like...? 的肯定回答是 Yes, please.；否定是 No, thanks." },
      { type: "choice", stage: "practice", difficulty: 2, stem: "I'd like ____ soup and rice, please.", options: ["a", "an", "some", "two"], answer: "C", hint: "soup 不可数。", explanation: "soup 是不可数名词，用 some（一些）修饰，不能用 a/two。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全对话：— What's ____ dinner? — Some chicken and rice.", answer: "for", hint: "三餐前用什么介词？", explanation: "What's for dinner? 是固定句型，三餐前用 for。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "妈妈喊大家吃饭，她会说（ ）", options: ["Dinner's ready!", "What would you like?", "Help yourself.", "Pass me the bowl."], answer: "A", hint: "“晚饭好了！”", explanation: "Dinner's ready! 表示“晚饭好了，可以吃了”。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— What would you like? — I'd like some ____, please.（选择语法正确的食物项）", options: ["vegetable", "vegetables", "a vegetable soup noodle", "soups"], answer: "B", hint: "可数名词用复数，不可数名词不加 s。", explanation: "vegetable 常用复数 vegetables；soup 不可数不能加 s。" },
    ],
  },
  {
    code: "G4-EN-5-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 5 Dinner's ready",
    title: "语音与情景：e 的长音 /iː/（he, she, we, me）与用餐对话",
    sortOrder: 0,
    summary: [
      { heading: "e 发 /iː/", body: "字母 e 在开音节中发长音 /iː/，如：he（他）、she（她）、we（我们）、me（我，宾格）、be。这些词都以 e 结尾，e 发字母音。" },
      { heading: "对比记忆", body: "e 在闭音节常发 /e/，如 bed（床）、red（红色）、pen（钢笔）。对比：he /iː/ — bed /e/。" },
      { heading: "情景对话", body: "用餐对话串起来：— What's for dinner? — What would you like? — I'd like some beef, please. — Here you are. — Thanks. 注意礼貌词 please 和 thanks。" },
    ],
    example: {
      stem: "找出 e 发 /iː/ 的单词：she, bed, pen, red。",
      analysis: "she 以 e 结尾是开音节，e 发 /iː/；bed、pen、red 中 e 发 /e/。",
      answer: "she",
    },
    prereqCodes: ["G4-EN-5-02"],
    commonErrors: [
      { cause: "发音混淆", detail: "把 she 读成 /ʃe/，he、she、we、me 中 e 都发长音 /iː/。" },
      { cause: "代词误用", detail: "me 是宾格（用在动词后），主语要用 I：Help yourself to the fish. 不能说 Help you." },
    ],
    socratic: {
      keyConcepts: ["e 发 /iː/", "开音节", "用餐礼貌用语"],
      probes: ["he、she、we、me 发音有什么共同点？", "bed 和 she 中 e 的发音一样吗？"],
      hints: ["以 e 结尾的单音节词，e 常读字母音 /iː/。", "读一读 she 和 bed，对比 e 的长短。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中 e 发 /iː/ 的是（ ）", options: ["bed", "we", "pen", "red"], answer: "B", hint: "找以 e 结尾的词。", explanation: "we 以 e 结尾，e 发 /iː/；bed、pen、red 中 e 发 /e/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "he、she、we、me 中字母 e 的发音（ ）", options: ["都不同", "都发 /e/", "都发 /iː/", "有的 /iː/ 有的 /e/"], answer: "C", hint: "都是开音节词。", explanation: "这四个词都以 e 结尾，e 都发长音 /iː/。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "— Would you like some fish? — No, ____.（婉拒）", options: ["please", "thanks", "I don't", "yes"], answer: "B", hint: "礼貌地拒绝。", explanation: "婉拒说 No, thanks.；接受说 Yes, please." },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全对话：— Here you are. — ____（谢谢）", answer: "thanks|thank you", hint: "表示感谢。", explanation: "别人递东西给你，说 Thanks. / Thank you. 表示感谢。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词 e 的发音都相同？（ ）", options: ["he, she, me", "he, bed, she", "we, pen, red", "me, red, bed"], answer: "A", hint: "都以 e 结尾吗？", explanation: "he、she、me 都以 e 结尾，e 都发 /iː/。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "请客人随便吃，应该说（ ）", options: ["Help yourself.", "Help you.", "Help me.", "You help."], answer: "A", hint: "yourself 是“你自己”。", explanation: "Help yourself. 是餐桌用语“请自便、随便吃”。" },
    ],
  },
  {
    code: "G4-EN-6-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 6 Meet my family",
    title: "家庭成员与职业词汇：parents, uncle, aunt, doctor, nurse, driver",
    sortOrder: 0,
    summary: [
      { heading: "家庭成员", body: "parents（父母，复数）、father/dad（爸爸）、mother/mum（妈妈）、uncle（叔叔/舅舅）、aunt（阿姨/姑姑）、cousin（堂/表兄弟姐妹）、baby brother（小弟弟）。如：My family has six people.（我家有六口人。）" },
      { heading: "职业词汇", body: "doctor（医生）、nurse（护士）、driver（司机）、farmer（农民）、cook（厨师）。如：My father is a doctor.（我爸爸是一名医生。）" },
      { heading: "a/an 用法", body: "职业前用 a/an：a doctor, a nurse, a driver, a farmer, a cook，这些词都以辅音音素开头，都用 a。" },
    ],
    example: {
      stem: "连一连：在医院给病人看病的人、开车的人、做饭的人分别是哪种职业？",
      analysis: "看病的是 doctor（医生），开车的是 driver（司机），做饭的是 cook（厨师）。",
      answer: "doctor, driver, cook",
    },
    prereqCodes: ["G4-EN-5-01"],
    commonErrors: [
      { cause: "词义混淆", detail: "cook 是“厨师”（名词），也是“做饭”（动词）；\"cooker\" 是炊具，不是厨师。" },
      { cause: "parents 单复数", detail: "parents 指“父母两人”是复数：My parents are...；说“父/母一方”用 parent。" },
    ],
    socratic: {
      keyConcepts: ["家庭成员词汇", "职业词汇", "a + 职业"],
      probes: ["你能用英语说出家里所有成员吗？", "cook 和 cooker 哪个是厨师？"],
      hints: ["father、mother 的口语是 dad、mum。", "职业词前加 a：a doctor, a nurse。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“医生”用英语说是（ ）", options: ["nurse", "doctor", "driver", "farmer"], answer: "B", hint: "在医院看病的。", explanation: "doctor 是“医生”，nurse 是“护士”。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "“厨师”用英语说是（ ）", options: ["cooker", "cook", "cookie", "cooking"], answer: "B", hint: "cooker 是炊具。", explanation: "cook 是“厨师”；cooker 是“炊具”，注意不要混淆。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "My parents ____ both doctors.", options: ["is", "are", "am", "be"], answer: "B", hint: "parents 是复数。", explanation: "parents 指父母两人，是复数，be 动词用 are。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写单词）：护士 ____", answer: "nurse", hint: "n-u-r-s-e。", explanation: "“护士”是 nurse，注意与 doctor 区分。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "My uncle is ____ driver.", options: ["a", "an", "the", "/"], answer: "A", hint: "driver 以辅音音素开头。", explanation: "driver 以辅音音素 /d/ 开头，职业前用 a。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "“我家有六口人。”英语是（ ）", options: ["My family have six people.", "My family has six people.", "My family is six people.", "My family are six people."], answer: "B", hint: "family 作整体，用 has。", explanation: "family 作整体看待，第三人称单数用 has：My family has six people." },
    ],
  },
  {
    code: "G4-EN-6-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 6 Meet my family",
    title: "核心句型：How many people...? / What's your aunt's job?",
    sortOrder: 0,
    summary: [
      { heading: "询问数量", body: "How many people are there in your family?（你家有几口人？）— Three. / My family has three people. How many + 复数名词。" },
      { heading: "询问职业", body: "What's your aunt's job?（你阿姨是做什么工作的？）— She's a nurse.（她是一名护士。）“某人的”用 's：your aunt's job。" },
      { heading: "综合介绍", body: "Come and meet my family!（来见见我的家人！）This is my uncle. He's tall and strong. He's a football player. 介绍 = 成员 + 外貌 + 职业。" },
    ],
    example: {
      stem: "— ____ your father's job? — He's a driver.",
      analysis: "回答是职业（司机），问句用 What's ... job? 句型。",
      answer: "What's",
    },
    prereqCodes: ["G4-EN-6-01"],
    commonErrors: [
      { cause: "how many 后接单数", detail: "How many people 中 people 本身是复数，不能说 \"how many person\"；how many 后必须接复数名词。" },
      { cause: "答非所问", detail: "What's your father's job? 回答外貌 He's tall. 错误，应回答职业 He's a driver." },
    ],
    socratic: {
      keyConcepts: ["How many + 复数", "What's ... job?", "'s 所有格"],
      probes: ["问“几口人”和问“什么工作”分别用哪个句型？", "your aunt's job 中 's 表示什么？"],
      hints: ["how many 后面跟复数名词。", "问职业：What's + 某人的 + job?"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— What's your mother's job? — ____", options: ["She's tall.", "She's a nurse.", "She's my mum.", "She's in the kitchen."], answer: "B", hint: "问的是职业。", explanation: "问职业用职业回答：She's a nurse.（她是护士。）" },
      { type: "choice", stage: "check", difficulty: 1, stem: "How many ____ are there in your family?", options: ["people", "person", "peoples", "a people"], answer: "A", hint: "people 本身就是复数。", explanation: "people 是复数形式（人们），how many 后接复数，people 不加 s。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— ____ people are there in your family? — Five.", options: ["How much", "How many", "How old", "How"], answer: "B", hint: "问可数数量。", explanation: "问可数名词数量用 How many；how much 问不可数量或价格。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全句子：What's your uncle's ____? — He's a cook.", answer: "job", hint: "问“工作”的词。", explanation: "What's ... job? 用于询问职业。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列句子正确的是（ ）", options: ["What's your aunt job?", "What's your aunts' job?", "What's your aunt's job?", "What your aunt's job?"], answer: "C", hint: "“阿姨的”要加 's，且不能漏 be 动词。", explanation: "“某人的”用 's：your aunt's；句中要有 is（'s）。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— How many people are there in your family? — ____（我家有五口人。）", options: ["My family have five people.", "My family has five people.", "There has five people.", "My family is five."], answer: "B", hint: "family 作整体用 has。", explanation: "My family has five people. 是规范表达，family 作整体，用 has。" },
    ],
  },
  {
    code: "G4-EN-6-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 6 Meet my family",
    title: "语音与运用：a/e/i/o/u 长短音综合复习 + 介绍家庭",
    sortOrder: 0,
    summary: [
      { heading: "长短音综合", body: "元音字母 + 辅音 + e（开音节）读字母音：a-e /eɪ/ cake, i-e /aɪ/ kite, o-e /əʊ/ nose, u-e /juː/ use；闭音节读短音：a /æ/ cat, e /e/ bed, i /ɪ/ big, o /ɒ/ dog, u /ʌ/ bus。" },
      { heading: "判断方法", body: "先看单词结尾有没有不发音的 e：有 e → 元音读字母音（长音）；没有 e → 元音读短音。如：hat—hate, bit—bite, not—note, us—use。" },
      { heading: "介绍家庭综合", body: "介绍家庭：This is my family. My father is a doctor. He is tall. My mother is a nurse. She is friendly. I love my family!（我爱我家！）" },
    ],
    example: {
      stem: "给单词分类：cake, cat, kite, big, nose, dog —— 哪些元音发长音？",
      analysis: "cake（a-e）、kite（i-e）、nose（o-e）有结尾 e，元音发字母音；cat、big、dog 发短音。",
      answer: "发长音：cake, kite, nose；发短音：cat, big, dog。",
    },
    prereqCodes: ["G4-EN-6-02"],
    commonErrors: [
      { cause: "规则误用", detail: "看到结尾 e 就读出声，如把 kite 读成 /kaɪtə/；结尾 e 永远不发音。" },
      { cause: "长短音混淆", detail: "把 dog 读成 /dəʊg/，闭音节 o 读 /ɒ/，不要读成字母音。" },
    ],
    socratic: {
      keyConcepts: ["开音节与闭音节", "五个元音的长短音", "结尾 e 的作用"],
      probes: ["怎么快速判断一个单词里的元音读长音还是短音？", "us 和 use、hat 和 hate 发音差在哪里？"],
      hints: ["看结尾有没有不发音的 e。", "把五组长短音各读一遍：cat-cake, bed-he, big-kite, dog-nose, bus-use。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中元音发短音的是（ ）", options: ["cake", "cat", "kite", "nose"], answer: "B", hint: "没有结尾 e 的。", explanation: "cat 是闭音节，a 发 /æ/；cake、kite、nose 元音发字母音。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "hat 和 hate 中 a 的发音（ ）", options: ["相同", "hate 中发 /eɪ/，hat 中发 /æ/", "hat 中发 /eɪ/", "都不发音"], answer: "B", hint: "结尾 e 的作用。", explanation: "hat 闭音节 a 发 /æ/；hate 是 a-e 结构，a 发 /eɪ/。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "与 use 中 u 发音规律相同的一组是（ ）", options: ["cake, kite, nose", "cat, big, dog", "bus, duck, mum", "hat, bed, sit"], answer: "A", hint: "use 是 u-e 结构。", explanation: "cake（a-e）、kite（i-e）、nose（o-e）与 use（u-e）都是元音+辅音+e 结构，元音发字母音。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全介绍：This is my father. He is a ____.（医生）", answer: "doctor", hint: "d-o-c-t-o-r。", explanation: "“医生”是 doctor，a doctor 表示“一名医生”。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词元音都发短音？（ ）", options: ["cat, bed, big", "cake, kite, use", "cat, cake, dog", "bed, nose, bus"], answer: "A", hint: "都是闭音节吗？", explanation: "cat /æ/、bed /e/、big /ɪ/ 都是闭音节短音。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "介绍自己的家庭，开头最合适的是（ ）", options: ["This is my family.", "What's your job?", "How many people?", "Help yourself."], answer: "A", hint: "先总体介绍。", explanation: "介绍家庭以 This is my family.（这是我的家庭。）开头最自然。" },
    ],
  },
  {
    code: "G4-EN-11-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 1 My school",
    title: "学校场所词汇：library, playground, teachers' office, computer room",
    sortOrder: 0,
    summary: [
      { heading: "场所词汇", body: "library（图书馆）、playground（操场）、teachers' office（教师办公室）、computer room（计算机房）、music room（音乐教室）、art room（美术教室）。如：This is the library.（这是图书馆。）" },
      { heading: "楼层表达", body: "the first floor（一楼）、the second floor（二楼）。注意：序数词 first、second 前要加 the。It's on the second floor.（它在二楼。）" },
      { heading: "teachers' office", body: "teachers' 是复数名词 teachers 的所有格，以 s 结尾的复数只加 '：teachers' office（老师们的办公室）。" },
    ],
    example: {
      stem: "用英语说：图书馆在一楼。",
      analysis: "“图书馆”是 the library，“在一楼”用 on the first floor，be 动词用 is。",
      answer: "The library is on the first floor.",
    },
    prereqCodes: ["G4-EN-6-01"],
    commonErrors: [
      { cause: "序数词漏 the", detail: "写成 \"on first floor\"，序数词 first/second 前必须加 the。" },
      { cause: "拼写错误", detail: "把 library 写成 \"libary\"，漏掉 r；teachers' office 的撇号位置写错。" },
    ],
    socratic: {
      keyConcepts: ["学校场所词汇", "on the first/second floor", "名词所有格 's / s'"],
      probes: ["你的学校里有哪些场所？图书馆在几楼？", "为什么 teachers' 的撇号在 s 后面？"],
      hints: ["first、second 前面别忘了 the。", "以 s 结尾的复数名词，所有格只加撇号。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“图书馆”用英语说是（ ）", options: ["playground", "library", "computer room", "art room"], answer: "B", hint: "很多书的地方。", explanation: "library 是“图书馆”；playground 操场，computer room 计算机房。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "The music room is on ____ second floor.", options: ["a", "an", "the", "/"], answer: "C", hint: "序数词前用什么？", explanation: "序数词 second 前要用定冠词 the：on the second floor。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "上体育课的地方通常是（ ）", options: ["library", "playground", "teachers' office", "computer room"], answer: "B", hint: "运动的地方。", explanation: "playground 是“操场”，上体育课的地方。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全句子：The library is on the ____ floor.（一楼）", answer: "first", hint: "“第一”的序数词。", explanation: "“一楼”是 the first floor，first 前已有 the。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "“教师办公室”正确写法是（ ）", options: ["teacher's office", "teachers' office", "teachers office", "teachering office"], answer: "B", hint: "很多老师共用的办公室。", explanation: "复数 teachers 以 s 结尾，所有格只加 '：teachers' office。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "汉译英（写单词）：操场 ____", answer: "playground", hint: "play + ground。", explanation: "playground 由 play（玩）+ ground（场地）组成，意为“操场”。" },
    ],
  },
  {
    code: "G4-EN-11-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 1 My school",
    title: "核心句型：Where's the library? / Is this/that the...? / Do you have...?",
    sortOrder: 0,
    summary: [
      { heading: "询问位置", body: "Where's the teachers' office?（教师办公室在哪里？）— It's on the second floor.（它在二楼。）" },
      { heading: "this 与 that", body: "Is this the library?（这是图书馆吗？近处用 this）/ Is that the computer room?（那是计算机房吗？远处用 that）回答用 it：Yes, it is. / No, it isn't." },
      { heading: "询问设施", body: "Do you have a library?（你们有图书馆吗？）— Yes, we do. 一般疑问句用 do 提问，用 do 回答。" },
    ],
    example: {
      stem: "— Is that the playground? — No, it ____.（否定回答）",
      analysis: "Is that...? 的回答用 it 指代，否定为 No, it isn't. ",
      answer: "isn't",
    },
    prereqCodes: ["G4-EN-11-01"],
    commonErrors: [
      { cause: "this/that 混淆", detail: "近处的东西用 this（这个），远处用 that（那个），指着远处的楼却说 this 是错误。" },
      { cause: "回答不一致", detail: "Do you have...? 却回答 Yes, I have. 规范回答是 Yes, we do. / No, we don't." },
    ],
    socratic: {
      keyConcepts: ["Where's the...?", "Is this/that...?", "Do you have...? 的回答"],
      probes: ["指着近处的房间和远处的房间，分别用 this 还是 that？", "Do you have...? 用什么词回答？"],
      hints: ["近 this 远 that，回答都用 it。", "do 问 do 答。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— ____ the library? — It's on the first floor.", options: ["Where", "Where's", "What's", "Is"], answer: "B", hint: "问地点且要有 be 动词。", explanation: "Where's = Where is，询问“图书馆在哪里”。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "指着远处的操场问“那是操场吗？”，应说（ ）", options: ["Is this the playground?", "Is that the playground?", "This is the playground.", "Where the playground?"], answer: "B", hint: "远处用 that。", explanation: "远处的事物用 that：Is that the playground?" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— Do you have a music room? — ____, we do.", options: ["Yes", "No", "Not", "Do"], answer: "A", hint: "肯定回答。", explanation: "Do you have...? 的肯定回答是 Yes, we do.；否定是 No, we don't." },
      { type: "fill", stage: "practice", difficulty: 2, stem: "— Is this the art room? — No, it ____.（否定回答）", answer: "isn't|is not", hint: "is 的否定形式。", explanation: "Is this...? 的否定回答是 No, it isn't.（is not 的缩写）。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列对话正确的是（ ）", options: ["— Where's the library? — It's on the first floor.", "— Where's the library? — Yes, it is.", "— Where the library? — On first floor.", "— Where's library? — It's the first floor."], answer: "A", hint: "问地点，答位置。", explanation: "Where's 问地点，回答 It's on the first floor.；其他选项漏词或答非所问。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— Is that the computer room? — No, it isn't. It's the ____.（美术教室）", options: ["art room", "arts room", "art's room", "room art"], answer: "A", hint: "art + room。", explanation: "“美术教室”是 art room，名词修饰名词，art 不加 s。" },
    ],
  },
  {
    code: "G4-EN-11-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 1 My school",
    title: "语音：字母组合 er 发 /ə/（water, tiger, sister, dinner）",
    sortOrder: 0,
    summary: [
      { heading: "er 发 /ə/", body: "字母组合 er 在词尾常发短促的 /ə/（像轻声“呃”）。如：water（水）、tiger（老虎）、sister（姐妹）、dinner（晚饭）、computer（电脑）。" },
      { heading: "发音位置", body: "er 发 /ə/ 时舌头放松，声音又短又轻，重音在单词前面的音节：WAter, TIger, DINner。" },
      { heading: "拼写提示", body: "听到词尾 /ə/ 的音，常拼写为 er：sist + er = sister，din + ner = dinner（注意 dinner 双写 n）。" },
    ],
    example: {
      stem: "读一读 water, tiger, sister，找出它们共同的字母组合和发音。",
      analysis: "三个词都以 er 结尾，er 都发 /ə/。",
      answer: "共同字母组合是 er，发 /ə/。",
    },
    prereqCodes: ["G4-EN-11-02"],
    commonErrors: [
      { cause: "发音过重", detail: "把词尾 er 读成重重的 /ɜː/ 或“儿”音，词尾 er 应读轻短的 /ə/。" },
      { cause: "拼写混淆", detail: "把 water 写成 \"wator\"，sister 写成 \"sistur\"，记住词尾这个音常拼作 er。" },
    ],
    socratic: {
      keyConcepts: ["er 发 /ə/", "重音在前面音节", "er 的拼写"],
      probes: ["water 和 tiger 词尾发音有什么共同点？", "sister 的重音在第几个音节？"],
      hints: ["读 water 时，后面的 ter 又轻又短。", "把 water、sister、dinner 各读三遍，感受词尾的音。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中 er 发 /ə/ 的是（ ）", options: ["water", "her", "term", "verb"], answer: "A", hint: "词尾的 er 读轻音。", explanation: "water 词尾 er 发 /ə/；her、term 中 er 发 /ɜː/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "sister 一词的重音在（ ）", options: ["第一个音节", "第二个音节", "两个一样重", "没有重音"], answer: "A", hint: "SIS-ter。", explanation: "sister 读 /ˈsɪstə/，重音在第一个音节，词尾 er 轻读。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "与 tiger 词尾发音相同的是（ ）", options: ["dinner", "her", "ruler 中的 u", "bird"], answer: "A", hint: "tiger 词尾发 /ə/。", explanation: "dinner 词尾 er 也发 /ə/，与 tiger 相同。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：wat__（水）", answer: "er", hint: "发 /ə/ 的字母组合。", explanation: "water 以 er 结尾，er 发 /ə/。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词 er 都发 /ə/？（ ）", options: ["water, sister, computer", "water, her, sister", "tiger, term, dinner", "her, term, verb"], answer: "A", hint: "找词尾轻读的 er。", explanation: "water、sister、computer 词尾 er 都发 /ə/。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "补全单词：sist__（姐妹）", answer: "er", hint: "词尾发 /ə/。", explanation: "sister 以 er 结尾，意为“姐妹”。" },
    ],
  },
  {
    code: "G4-EN-12-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 2 What time is it?",
    title: "日常活动词汇：breakfast, lunch, dinner, English class, PE class",
    sortOrder: 0,
    summary: [
      { heading: "一日三餐", body: "breakfast（早餐）、lunch（午餐）、dinner（晚餐）。如：It's time for lunch.（该吃午饭了。）" },
      { heading: "课程与活动", body: "English class（英语课）、music class（音乐课）、PE class（体育课）、get up（起床）、go to school（去上学）、go home（回家）、go to bed（上床睡觉）。" },
      { heading: "三餐前的表达", body: "“吃早餐”用 have breakfast，三餐前不加 the；课程名称中 English、PE 首字母大写。" },
    ],
    example: {
      stem: "把活动和英文连线：起床、去上学、回家、睡觉。",
      analysis: "起床 get up，去上学 go to school，回家 go home，睡觉 go to bed。",
      answer: "get up, go to school, go home, go to bed",
    },
    prereqCodes: ["G4-EN-11-01"],
    commonErrors: [
      { cause: "大小写错误", detail: "English、PE 首字母必须大写：English class、PE class，写成 english class 错误。" },
      { cause: "拼写错误", detail: "breakfast 拼写容易错：break + fast，不要写成 \"brekfast\"。" },
    ],
    socratic: {
      keyConcepts: ["三餐词汇", "动词短语 get up/go to...", "课程名称大小写"],
      probes: ["你一天的时间安排是什么？能用英语说出三件事吗？", "为什么 English 要大写而 class 不用？"],
      hints: ["breakfast = break + fast。", "go + to + 地点：go to school, go to bed；但 go home 不加 to。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“早餐”用英语说是（ ）", options: ["lunch", "dinner", "breakfast", "supper time"], answer: "C", hint: "break + fast。", explanation: "breakfast 是“早餐”；lunch 午餐，dinner 晚餐。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "下列书写正确的是（ ）", options: ["english class", "English class", "English Class 都可以但 english 也可小写", "ENGLISH class"], answer: "B", hint: "语言名称大写。", explanation: "语言名称 English 首字母大写，class 小写：English class。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "晚上九点该做的事是（ ）", options: ["get up", "go to school", "go to bed", "have lunch"], answer: "C", hint: "晚上该睡觉了。", explanation: "go to bed 意为“上床睡觉”，符合晚上九点的时间。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写短语）：起床 ____", answer: "get up", hint: "g-e-t u-p。", explanation: "“起床”是 get up。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列短语正确的是（ ）", options: ["go to home", "go home", "go to bed 和 go home 中 home 前加 to", "go at school"], answer: "B", hint: "home 前不加 to。", explanation: "go home 是固定用法，home 前不加 to；go to school / go to bed 才加 to。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "补全句子：It's 12 o'clock. It's time for ____.（午餐）", answer: "lunch", hint: "中午十二点吃什么？", explanation: "中午十二点是午餐时间 lunch。" },
    ],
  },
  {
    code: "G4-EN-12-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 2 What time is it?",
    title: "核心句型：What time is it? / It's time for/to...",
    sortOrder: 0,
    summary: [
      { heading: "询问时间", body: "What time is it?（几点了？）— It's 9 o'clock.（九点了。）It's 7:30.（七点半。）整点用 数字 + o'clock。" },
      { heading: "It's time for + 名词", body: "It's time for lunch.（该吃午饭了。）for 后面接名词：for breakfast, for English class, for bed。" },
      { heading: "It's time to + 动词", body: "It's time to get up.（该起床了。）to 后面接动词原形：to go to school, to go home。口诀：for 后接名词，to 后接动词。" },
    ],
    example: {
      stem: "选择：It's time ____ go to school.（for / to）",
      analysis: "go 是动词原形，前面用 to；for 后接名词。",
      answer: "to",
    },
    prereqCodes: ["G4-EN-12-01"],
    commonErrors: [
      { cause: "for/to 混用", detail: "It's time for get up. 错误，动词前用 to：It's time to get up.；名词前用 for：It's time for lunch." },
      { cause: "o'clock 误用", detail: "非整点不能说 \"7:30 o'clock\"，o'clock 只用于整点：9 o'clock。" },
    ],
    socratic: {
      keyConcepts: ["What time is it?", "It's time for + 名词", "It's time to + 动词原形"],
      probes: ["It's time for lunch 和 It's time to have lunch 意思一样吗？结构差在哪里？", "七点半可以说 7:30 o'clock 吗？为什么？"],
      hints: ["名词前 for，动词前 to。", "o'clock 只跟在整点后面。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— ____ is it? — It's 8 o'clock.", options: ["What", "What time", "How", "Where"], answer: "B", hint: "问时间的固定句型。", explanation: "询问时间用 What time is it?" },
      { type: "choice", stage: "check", difficulty: 1, stem: "It's time ____ English class.（该上英语课了。）", options: ["to", "for", "at", "in"], answer: "B", hint: "English class 是名词。", explanation: "名词前用 for：It's time for English class." },
      { type: "choice", stage: "practice", difficulty: 2, stem: "It's time ____ get up.（该起床了。）", options: ["for", "to", "at", "on"], answer: "B", hint: "get up 是动词短语。", explanation: "动词原形前用 to：It's time to get up." },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全对话：— What time is it? — It's 9 ____.（九点整）", answer: "o'clock", hint: "整点后面的词。", explanation: "整点表达：数字 + o'clock，9 o'clock 九点整。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列句子正确的是（ ）", options: ["It's time for go home.", "It's time to go home.", "It's time to home.", "It's time for go to home."], answer: "B", hint: "动词前用 to，home 前不加 to。", explanation: "go home 是动词短语且 home 前不加 to：It's time to go home." },
      { type: "choice", stage: "variant", difficulty: 3, stem: "“该吃晚饭了”的正确英语是（ ）", options: ["It's time to dinner.", "It's time for dinner.", "It's time for have dinner.", "It's time eat dinner."], answer: "B", hint: "dinner 是名词。", explanation: "名词 dinner 前用 for：It's time for dinner. 也可说 It's time to have dinner." },
    ],
  },
  {
    code: "G4-EN-12-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 2 What time is it?",
    title: "语音：字母组合 ir/ur 发 /ɜː/（girl, bird, nurse, hamburger）",
    sortOrder: 0,
    summary: [
      { heading: "ir 发 /ɜː/", body: "字母组合 ir 常发 /ɜː/（长长的“呃”）。如：girl（女孩）、bird（鸟）、shirt（衬衫）、first（第一）。" },
      { heading: "ur 发 /ɜː/", body: "字母组合 ur 也常发 /ɜː/。如：nurse（护士）、hamburger（汉堡包）、hurt（受伤）、turn（转弯）。" },
      { heading: "对比 er", body: "词中的 er 也常发 /ɜː/（her, term），但词尾的 er 读轻音 /ə/（water）。ir 和 ur 一般都读 /ɜː/，拼写要记牢。" },
    ],
    example: {
      stem: "girl 和 bird 中画线部分 ir 发音相同吗？nurse 中的 ur 呢？",
      analysis: "girl、bird 中 ir 发 /ɜː/，nurse 中 ur 也发 /ɜː/，三者发音相同。",
      answer: "都相同，ir 和 ur 都发 /ɜː/。",
    },
    prereqCodes: ["G4-EN-12-02"],
    commonErrors: [
      { cause: "拼写混淆", detail: "把 bird 写成 \"brid\"，把 girl 写成 \"gril\"，ir 的字母顺序记错。" },
      { cause: "ir/ur 混用", detail: "把 nurse 写成 \"nirse\"，shirt 写成 \"shurt\"，要靠单词记忆区分 ir 和 ur。" },
    ],
    socratic: {
      keyConcepts: ["ir 发 /ɜː/", "ur 发 /ɜː/", "与词尾 er /ə/ 的区别"],
      probes: ["girl 里的 ir 和 water 里的 er 发音一样吗？", "你能各举两个 ir 和 ur 的单词吗？"],
      hints: ["ir 和 ur 都发长长的 /ɜː/。", "bird, girl 是 ir；nurse, hamburger 是 ur。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "girl 中 ir 的发音是（ ）", options: ["/ə/", "/ɜː/", "/ɪ/", "/eɪ/"], answer: "B", hint: "长长的“呃”。", explanation: "girl 中 ir 发 /ɜː/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中 ur 发 /ɜː/ 的是（ ）", options: ["nurse", "ruler", "use", "cute"], answer: "A", hint: "护士。", explanation: "nurse 中 ur 发 /ɜː/；ruler、use、cute 中 u 发 /uː/ 或 /juː/。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "与 bird 中 ir 发音相同的是（ ）", options: ["shirt", "water 的 er", "sister 的 er", "big 的 i"], answer: "A", hint: "bird 的 ir 发 /ɜː/。", explanation: "shirt 中 ir 也发 /ɜː/；water、sister 词尾 er 发 /ə/。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：b__d（鸟）", answer: "ir", hint: "发 /ɜː/ 的字母组合。", explanation: "bird 的拼写是 b-i-r-d，ir 发 /ɜː/。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词画线部分发音都相同？（ ）", options: ["girl, bird, nurse", "girl, water, bird", "nurse, sister, hamburger", "bird, tiger, shirt"], answer: "A", hint: "ir 和 ur 都发 /ɜː/。", explanation: "girl（ir）、bird（ir）、nurse（ur）都发 /ɜː/。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "补全单词：n__se（护士）", answer: "ur", hint: "发 /ɜː/，用 ur。", explanation: "nurse 的拼写是 n-u-r-s-e，ur 发 /ɜː/。" },
    ],
  },
  {
    code: "G4-EN-13-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 3 Weather",
    title: "天气词汇：sunny, windy, cloudy, snowy, rainy, warm, cool, cold, hot",
    sortOrder: 0,
    summary: [
      { heading: "天气状况", body: "sunny（晴朗的）、windy（多风的）、cloudy（多云的）、snowy（下雪的）、rainy（下雨的）。名词 + y 变形容词：sun→sunny, wind→windy, cloud→cloudy。" },
      { heading: "温度感受", body: "hot（热的）、warm（温暖的）、cool（凉爽的）、cold（寒冷的）。如：It's warm in Beijing today.（今天北京很暖和。）" },
      { heading: "构词规律", body: "名词变形容词加 y：rain→rainy, snow→snowy, wind→windy, cloud→cloudy；注意 sun 双写 n：sun→sunny。" },
    ],
    example: {
      stem: "用英语说：今天有风而且凉爽。",
      analysis: "“多风的”是 windy，“凉爽的”是 cool，用 It's... 句型。",
      answer: "It's windy and cool today.",
    },
    prereqCodes: ["G4-EN-12-01"],
    commonErrors: [
      { cause: "拼写错误", detail: "sun→sunny 要双写 n，写成 \"suny\" 错误；rainy 不加双写。" },
      { cause: "be 动词遗漏", detail: "说 \"It sunny today.\" 漏掉 is，应为 It's sunny today.；不能说 \"It's rain today\"，下雨用 rainy 或 It rains。" },
    ],
    socratic: {
      keyConcepts: ["名词 + y 变天气形容词", "温度词汇", "It's + 天气形容词"],
      probes: ["sun 变 sunny 为什么要双写 n？", "hot、warm、cool、cold 从热到冷怎么排序？"],
      hints: ["名词后面加 y，就变成“……的”。", "It's + 形容词 描述天气。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“晴朗的”用英语说是（ ）", options: ["cloudy", "sunny", "rainy", "windy"], answer: "B", hint: "sun + y，注意双写。", explanation: "sunny 意为“晴朗的”，由 sun 双写 n 加 y 构成。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "snow 变成形容词“下雪的”是（ ）", options: ["snowy", "snowey", "snowly", "snowing"], answer: "A", hint: "直接加 y。", explanation: "snow + y = snowy（下雪的）。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— It's ____ today. Let's fly kites!（今天有风。）", options: ["wind", "windy", "windyly", "winded"], answer: "B", hint: "名词 + y。", explanation: "描述天气用形容词 windy（多风的），wind 是名词。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写单词）：凉爽的 ____", answer: "cool", hint: "c-o-o-l。", explanation: "“凉爽的”是 cool，介于 warm 和 cold 之间。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列句子正确的是（ ）", options: ["It sunny today.", "It's sunny today.", "It's sun today.", "It sunny's today."], answer: "B", hint: "要有 be 动词，用形容词。", explanation: "描述天气用 It's + 形容词：It's sunny today." },
      { type: "choice", stage: "variant", difficulty: 3, stem: "冬天哈尔滨的天气，最合适的描述是（ ）", options: ["hot", "warm", "cold and snowy", "cool and sunny"], answer: "C", hint: "冬天北方又冷又下雪。", explanation: "哈尔滨冬天寒冷多雪：cold and snowy。" },
    ],
  },
  {
    code: "G4-EN-13-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 3 Weather",
    title: "核心句型：What's the weather like? / Can I...?",
    sortOrder: 0,
    summary: [
      { heading: "询问天气", body: "What's the weather like in Beijing?（北京天气怎么样？）— It's sunny and warm.（晴朗又暖和。）句中 like 是介词“像”，不能漏。" },
      { heading: "请求许可", body: "Can I go outside?（我能出去吗？）— Yes, you can. / No, you can't.（不行。）妈妈还会说：It's cold outside. Put on a hat.（外面冷，戴上帽子。）" },
      { heading: "小心烫", body: "Be careful! It's very hot.（小心！很烫。）hot 既可以指天气热，也可以指食物烫。" },
    ],
    example: {
      stem: "— What's the weather like today? — ____ （下雨了。）",
      analysis: "问天气，用 It's + 天气形容词回答，“下雨的”是 rainy。",
      answer: "It's rainy.",
    },
    prereqCodes: ["G4-EN-13-01"],
    commonErrors: [
      { cause: "漏掉 like", detail: "说成 \"What's the weather?\"，询问天气必须说 What's the weather like?" },
      { cause: "can 回答不一致", detail: "Can I...? 却回答 Yes, I do. 规范回答是 Yes, you can. / No, you can't." },
    ],
    socratic: {
      keyConcepts: ["What's the weather like?", "Can I...? 的回答", "can 问 can 答"],
      probes: ["What's the weather like? 里的 like 能去掉吗？", "Can I go outside? 妈妈同意和不同意分别怎么回答？"],
      hints: ["like 在这里是“像”的意思，不能少。", "can 提问，can 回答。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“北京天气怎么样？”英语是（ ）", options: ["What's the weather in Beijing?", "What's the weather like in Beijing?", "How's the weather like in Beijing?", "What weather in Beijing?"], answer: "B", hint: "句中要有 like。", explanation: "询问天气用 What's the weather like...? like 不能漏。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "— Can I go outside? — No, you ____.（否定回答）", options: ["can't", "don't", "aren't", "can"], answer: "A", hint: "can 的否定。", explanation: "Can I...? 的否定回答是 No, you can't." },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— What's the weather like in Shanghai? — ____", options: ["It's rainy.", "I like it.", "Yes, it is.", "It's a city."], answer: "A", hint: "用天气形容词回答。", explanation: "回答天气用 It's + 天气形容词：It's rainy." },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全对话：— Can I have some soup? — Yes, you ____. Be careful! It's hot.", answer: "can", hint: "肯定回答。", explanation: "Can I...? 的肯定回答是 Yes, you can." },
      { type: "choice", stage: "variant", difficulty: 2, stem: "汤很烫，妈妈提醒你小心，她会说（ ）", options: ["Be careful!", "Help yourself.", "It's cold.", "Go outside."], answer: "A", hint: "“小心！”", explanation: "Be careful! 表示“小心！”提醒别人注意。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "下列对话正确的是（ ）", options: ["— What's the weather like? — It's cold. Put on your coat.", "— What's the weather? — It's cold.", "— What's the weather like? — Yes, I can.", "— What weather like? — It's cold."], answer: "A", hint: "句型要完整，回答要匹配。", explanation: "正确句型 What's the weather like? 回答 It's cold.，并给出合理建议。" },
    ],
  },
  {
    code: "G4-EN-13-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 3 Weather",
    title: "语音：字母组合 ar 发 /ɑː/、al 发 /ɔː/（arm, car, tall, ball）",
    sortOrder: 0,
    summary: [
      { heading: "ar 发 /ɑː/", body: "字母组合 ar 常发 /ɑː/（张大嘴的“啊”）。如：arm（胳膊）、car（小汽车）、card（卡片）、farm（农场）、far（远的）。" },
      { heading: "al 发 /ɔː/", body: "字母组合 al 常发 /ɔː/。如：tall（高的）、ball（球）、wall（墙）、small（小的）。tall 和 ball 都押 /ɔːl/ 韵。" },
      { heading: "对比记忆", body: "car /kɑː/ 嘴张大；ball /bɔːl/ 嘴唇收圆。The tall girl has a ball. The car is far. 把单词放进句子里读。" },
    ],
    example: {
      stem: "判断 arm 和 car 中 ar 的发音是否相同；tall 和 ball 中 al 呢？",
      analysis: "arm、car 中 ar 都发 /ɑː/；tall、ball 中 al 都发 /ɔː/。",
      answer: "都相同：ar 发 /ɑː/，al 发 /ɔː/。",
    },
    prereqCodes: ["G4-EN-13-02"],
    commonErrors: [
      { cause: "发音不到位", detail: "把 car 读成短促的 /kæ/，ar 是长音 /ɑː/，要读饱满。" },
      { cause: "拼写混淆", detail: "把 ball 写成 \"bal\"（少一个 l），tall 写成 \"tal\"，al 后面常跟双写 ll。" },
    ],
    socratic: {
      keyConcepts: ["ar 发 /ɑː/", "al 发 /ɔː/", "长音要读饱满"],
      probes: ["car 和 card 中 ar 发音一样吗？", "tall、ball、wall 有什么共同的音？"],
      hints: ["ar 发长长的“啊”/ɑː/。", "al 发 /ɔː/，嘴唇圆圆的。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "car 中 ar 的发音是（ ）", options: ["/ɑː/", "/ɔː/", "/eɪ/", "/ə/"], answer: "A", hint: "张大嘴的长音。", explanation: "car 中 ar 发长音 /ɑː/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中 al 发 /ɔː/ 的是（ ）", options: ["tall", "car", "arm", "farm"], answer: "A", hint: "高的。", explanation: "tall 中 al 发 /ɔː/；car、arm、farm 中 ar 发 /ɑː/。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "与 ball 押韵的单词是（ ）", options: ["wall", "card", "far", "girl"], answer: "A", hint: "ball 读 /bɔːl/。", explanation: "wall 读 /wɔːl/，与 ball 押 /ɔːl/ 韵。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：__m（胳膊）", answer: "ar", hint: "发 /ɑː/ 的字母组合。", explanation: "arm 的拼写是 a-r-m，ar 发 /ɑː/。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词画线部分发音都相同？（ ）", options: ["arm, car, farm", "tall, car, ball", "arm, tall, small", "ball, card, wall"], answer: "A", hint: "都是 ar。", explanation: "arm、car、farm 中 ar 都发 /ɑː/。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "补全单词：t__l（高的）", answer: "al", hint: "发 /ɔː/，注意后面是 ll。", explanation: "tall 的拼写是 t-a-l-l，al 发 /ɔː/，结尾双写 l。" },
    ],
  },
  {
    code: "G4-EN-14-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 4 At the farm",
    title: "农场动植物词汇：hen, horse, cow, sheep, tomato, potato, carrot, green beans",
    sortOrder: 0,
    summary: [
      { heading: "动物词汇", body: "hen（母鸡）、horse（马）、cow（奶牛）、sheep（绵羊）、duck（鸭子）。sheep 单复数同形：a sheep 一只羊，many sheep 许多羊。" },
      { heading: "蔬菜词汇", body: "tomato（西红柿）、potato（土豆）、carrot（胡萝卜）、green beans（豆角）。如：I like tomatoes.（我喜欢西红柿。）" },
      { heading: "复数变化", body: "tomato→tomatoes, potato→potatoes（以 o 结尾加 es）；carrot→carrots（直接加 s）；sheep→sheep（不变）。" },
    ],
    example: {
      stem: "写出复数：tomato, potato, carrot, sheep。",
      analysis: "tomato、potato 以 o 结尾加 es；carrot 直接加 s；sheep 单复数同形。",
      answer: "tomatoes, potatoes, carrots, sheep",
    },
    prereqCodes: ["G4-EN-13-01"],
    commonErrors: [
      { cause: "复数变化错误", detail: "把 tomatoes 写成 \"tomatos\"，tomato、potato 变复数要加 es。" },
      { cause: "sheep 加 s", detail: "写成 \"sheeps\" 错误，sheep 单复数同形，two sheep 不是 two sheeps。" },
    ],
    socratic: {
      keyConcepts: ["农场词汇", "以 o 结尾加 es", "sheep 单复数同形"],
      probes: ["tomato 和 carrot 变复数的方式一样吗？", "一只羊和一群羊英语有什么区别？"],
      hints: ["有生命的 o 结尾名词常加 es：tomatoes, potatoes。", "sheep 永远不加 s。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“奶牛”用英语说是（ ）", options: ["hen", "horse", "cow", "sheep"], answer: "C", hint: "产牛奶的。", explanation: "cow 是“奶牛”；hen 母鸡，horse 马，sheep 绵羊。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "tomato 的复数是（ ）", options: ["tomatos", "tomatoes", "tomato", "tomatoe"], answer: "B", hint: "以 o 结尾。", explanation: "tomato 以 o 结尾，变复数加 es：tomatoes。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "There are two ____ on the farm.（农场里有两只绵羊。）", options: ["sheeps", "sheep", "sheepes", "a sheep"], answer: "B", hint: "sheep 单复数同形。", explanation: "sheep 单复数同形，two sheep 不加 s。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写单词）：胡萝卜 ____", answer: "carrot", hint: "c-a-r-r-o-t。", explanation: "“胡萝卜”是 carrot，注意双写 r。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "potato 的复数是（ ）", options: ["potatos", "potatoes", "potato", "potatoe"], answer: "B", hint: "和 tomato 一样。", explanation: "potato 以 o 结尾，变复数加 es：potatoes。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "下列复数形式正确的一组是（ ）", options: ["tomatoes, potatoes, carrots", "tomatos, potatos, carrots", "tomatoes, potatos, sheeps", "tomatos, potatoes, sheepes"], answer: "A", hint: "o 结尾加 es，carrot 加 s。", explanation: "tomato→tomatoes，potato→potatoes，carrot→carrots，sheep 不变。" },
    ],
  },
  {
    code: "G4-EN-14-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 4 At the farm",
    title: "核心句型：What are these/those? / Are these...? / How many...?",
    sortOrder: 0,
    summary: [
      { heading: "these 与 those", body: "these（这些，近处）、those（那些，远处），都指复数。What are these?（这些是什么？）— They're tomatoes.（它们是西红柿。）What are those? — They're horses." },
      { heading: "一般疑问句", body: "Are these carrots?（这些是胡萝卜吗？）— Yes, they are. / No, they aren't. 回答都用 they，不用 these/those。" },
      { heading: "询问数量", body: "How many horses do you have?（你有多少匹马？）— Seventeen. how many + 复数名词。" },
    ],
    example: {
      stem: "— What are those? — ____ hens.（那些是母鸡。）",
      analysis: "those 是复数，回答用 They're（They are），hen 变复数 hens。",
      answer: "They're",
    },
    prereqCodes: ["G4-EN-14-01"],
    commonErrors: [
      { cause: "these/those 混淆", detail: "近处用 these，远处用 those；指着远处的羊说 these 是错误。" },
      { cause: "单复数错误", detail: "回答 What are these? 用 It's... 错误，复数要用 They're...。" },
    ],
    socratic: {
      keyConcepts: ["these 与 those", "What are these/those?", "they 指代复数"],
      probes: ["these 和 those 都表示“复数”，区别在哪里？", "Are these...? 的回答为什么用 they 而不用 these？"],
      hints: ["近 these，远 those。", "问 these/those，答都用 they。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— What are these? — ____ tomatoes.", options: ["It's", "They're", "This is", "That is"], answer: "B", hint: "these 是复数。", explanation: "these 是复数，回答用 They're（They are）。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "指着远处的马群问，应说（ ）", options: ["What are these?", "What are those?", "What is this?", "What's that?"], answer: "B", hint: "远处 + 复数。", explanation: "远处的复数事物用 those：What are those?" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— Are these carrots? — No, ____. They're potatoes.", options: ["they are", "they aren't", "these aren't", "it isn't"], answer: "B", hint: "否定回答，用 they。", explanation: "Are these...? 的否定回答是 No, they aren't." },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全句子：____ many cows do you have? — Ten.", answer: "how", hint: "问数量的词组。", explanation: "How many + 复数名词，询问数量。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列对话正确的是（ ）", options: ["— What are those? — They're sheep.", "— What are those? — They're sheeps.", "— What are those? — It's a sheep.", "— What those? — They sheep."], answer: "A", hint: "sheep 复数不变，用 They're。", explanation: "复数回答用 They're，sheep 单复数同形：They're sheep." },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— How many ____ do you have? — Twelve.（选择合适的词）", options: ["horse", "horses", "horsies", "a horse"], answer: "B", hint: "how many 后接复数。", explanation: "how many 后接复数名词 horses。" },
    ],
  },
  {
    code: "G4-EN-14-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 4 At the farm",
    title: "语音：字母组合 or 发 /ɔː/ 与 /ɜː/（horse, fork, homework, world）",
    sortOrder: 0,
    summary: [
      { heading: "or 发 /ɔː/", body: "or 常发 /ɔː/。如：horse（马）、fork（叉子）、short（短的）、morning（早晨）、story（故事）。" },
      { heading: "or 发 /ɜː/", body: "or 在 w 后面常发 /ɜː/。如：homework（家庭作业）、world（世界）、work（工作）、word（单词）。" },
      { heading: "记忆窍门", body: "w + or → /ɜː/：work, word, world, homework；其余 or 多读 /ɔː/：horse, fork, morning。读一读：I do my homework and then ride a horse." },
    ],
    example: {
      stem: "horse 和 homework 中 or 的发音相同吗？",
      analysis: "horse 中 or 发 /ɔː/；homework 中 or 在 w 后，发 /ɜː/。",
      answer: "不同。horse 中 or 发 /ɔː/，homework 中 or 发 /ɜː/。",
    },
    prereqCodes: ["G4-EN-14-02"],
    commonErrors: [
      { cause: "发音混淆", detail: "把 homework 中的 or 读成 /ɔː/，w 后面的 or 要读 /ɜː/。" },
      { cause: "拼写错误", detail: "把 world 写成 \"wold\"，homework 写成 \"homwok\"，漏掉字母。" },
    ],
    socratic: {
      keyConcepts: ["or 发 /ɔː/", "w + or 发 /ɜː/", "对比记忆"],
      probes: ["horse 和 work 中 or 发音一样吗？什么影响了发音？", "你能各举两个 /ɔː/ 和 /ɜː/ 的 or 单词吗？"],
      hints: ["看见 w 在 or 前面，or 读 /ɜː/。", "读 horse 嘴圆，读 work 像长长的“呃”。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "horse 中 or 的发音是（ ）", options: ["/ɔː/", "/ɜː/", "/ə/", "/ɒ/"], answer: "A", hint: "马。", explanation: "horse 中 or 发 /ɔː/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中 or 发 /ɜː/ 的是（ ）", options: ["fork", "world", "horse", "morning"], answer: "B", hint: "w 后面的 or。", explanation: "world 中 or 在 w 后，发 /ɜː/；fork、horse、morning 中 or 发 /ɔː/。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "与 homework 中 or 发音相同的是（ ）", options: ["work", "fork", "short", "horse"], answer: "A", hint: "homework 的 or 发 /ɜː/。", explanation: "work 中 or 在 w 后发 /ɜː/，与 homework 相同。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：h__se（马）", answer: "or", hint: "发 /ɔː/ 的字母组合。", explanation: "horse 的拼写是 h-o-r-s-e，or 发 /ɔː/。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词 or 都发 /ɔː/？（ ）", options: ["horse, fork, short", "horse, world, work", "fork, word, morning", "short, work, horse"], answer: "A", hint: "避开 w + or。", explanation: "horse、fork、short 中 or 都发 /ɔː/。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "下列哪组单词 or 都发 /ɜː/？（ ）", options: ["work, word, world", "work, fork, word", "world, horse, work", "word, fork, short"], answer: "A", hint: "都是 w + or。", explanation: "work、word、world 都是 w + or，or 都发 /ɜː/。" },
    ],
  },
  {
    code: "G4-EN-15-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 5 My clothes",
    title: "衣物词汇：clothes, hat, skirt, dress, pants, shoes, jacket, sweater",
    sortOrder: 0,
    summary: [
      { heading: "衣物词汇", body: "clothes（衣服，总称）、hat（帽子）、skirt（女裙）、dress（连衣裙）、jacket（夹克）、sweater（毛衣）、coat（外套）、socks（袜子）、shoes（鞋子）、pants（裤子）。" },
      { heading: "成双成对的词", body: "shoes（鞋）、socks（袜子）、pants（裤子）常用复数形式：my shoes, these pants。说“一条裤子”用 a pair of pants。" },
      { heading: "put on 与 take off", body: "Put on your shirt.（穿上你的衬衫。）Take off your hat.（摘下你的帽子。）put on 穿上/戴上，take off 脱下/摘下。" },
    ],
    example: {
      stem: "选择：____ are my new shoes.（This / These）",
      analysis: "shoes 是复数，指示代词用 these（这些），this 用于单数。",
      answer: "These",
    },
    prereqCodes: ["G4-EN-14-01"],
    commonErrors: [
      { cause: "单复数误用", detail: "this shoes 错误，shoes 是复数，要用 these shoes；pants 也是复数。" },
      { cause: "词义混淆", detail: "skirt（短裙）和 dress（连衣裙）混淆；hat（有檐帽）是 PEP 用词。" },
    ],
    socratic: {
      keyConcepts: ["衣物词汇", "复数衣物 shoes/pants/socks", "put on / take off"],
      probes: ["为什么 shoes、pants 总是复数？", "put on 和 take off 是一对什么词？"],
      hints: ["鞋子、袜子、裤子都是成双的，用复数。", "天冷 put on your coat，进屋 take off your coat。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“连衣裙”用英语说是（ ）", options: ["skirt", "dress", "shirt", "sweater"], answer: "B", hint: "上下连在一起的裙子。", explanation: "dress 是“连衣裙”；skirt 是“短裙”。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词中常用复数形式的是（ ）", options: ["jacket", "sweater", "shoes", "hat"], answer: "C", hint: "成双的物品。", explanation: "shoes（鞋子）成双，常用复数；jacket、sweater、hat 用单数。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "____ on your coat. It's cold outside.", options: ["Take", "Put", "Look", "Get"], answer: "B", hint: "外面冷，要穿上。", explanation: "put on 意为“穿上”，take off 是“脱下”。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写单词）：毛衣 ____", answer: "sweater", hint: "s-w-e-a-t-e-r。", explanation: "“毛衣”是 sweater。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列表达正确的是（ ）", options: ["this pants", "these shoes", "this shoes", "these jacket"], answer: "B", hint: "单数 this，复数 these。", explanation: "shoes 复数用 these shoes；pants 复数用 these；jacket 单数用 this。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "进屋后妈妈让你摘下帽子，她说（ ）", options: ["Put on your hat.", "Take off your hat.", "Take on your hat.", "Put off your hat."], answer: "B", hint: "“摘下”用 take off。", explanation: "take off 意为“脱下、摘下”：Take off your hat." },
    ],
  },
  {
    code: "G4-EN-15-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 5 My clothes",
    title: "核心句型：Whose...? / Is this yours? / Are these...?",
    sortOrder: 0,
    summary: [
      { heading: "询问主人", body: "Whose coat is this?（这是谁的外套？）— It's mine.（是我的。）Whose pants are those?（那条裤子是谁的？）— They're your father's.（是你爸爸的。）" },
      { heading: "确认归属", body: "Is this yours?（这是你的吗？）— Yes, it is. / No, it isn't. Are these yours? — Yes, they are. / No, they aren't. 单数用 Is this，复数用 Are these。" },
      { heading: "名词性物主代词", body: "mine（我的）、yours（你的）后面不接名词：The coat is mine. 不能说 \"mine coat\"，要说 my coat。" },
    ],
    example: {
      stem: "— Whose skirt is this? — It's ____.（它是我的。）",
      analysis: "回答归属，后面没有名词，用名词性物主代词 mine（= my skirt）。",
      answer: "mine",
    },
    prereqCodes: ["G4-EN-15-01"],
    commonErrors: [
      { cause: "mine/my 混淆", detail: "说 \"It's mine skirt.\" 错误；mine 后不接名词（It's mine.），my 后必须接名词（It's my skirt.）。" },
      { cause: "单复数不一致", detail: "Whose pants is this? 错误，pants 是复数：Whose pants are these/those?" },
    ],
    socratic: {
      keyConcepts: ["Whose + 名词", "mine / yours", "'s 表示某人的"],
      probes: ["my coat 和 mine 有什么区别？什么时候用哪个？", "问一条裤子的主人，用 is this 还是 are these？为什么？"],
      hints: ["whose 问“谁的”。", "mine = my + 名词，后面不再接名词。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "— ____ coat is this? — It's Amy's.", options: ["Who", "Whose", "What", "Where"], answer: "B", hint: "问“谁的”。", explanation: "Whose 用于询问“谁的”：Whose coat is this?" },
      { type: "choice", stage: "check", difficulty: 1, stem: "— Is this your hat? — Yes, it's ____. ", options: ["my", "mine", "me", "I"], answer: "B", hint: "后面没有名词。", explanation: "后面没有名词，用名词性物主代词 mine（= my hat）。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "Whose pants ____ those?", options: ["is", "are", "am", "be"], answer: "B", hint: "pants 是复数。", explanation: "pants 是复数，be 动词用 are。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全对话：— Are these your socks? — No, they aren't. They're my ____（弟弟的）.", answer: "brother's", hint: "表示“某人的”加 's。", explanation: "表示“弟弟的”用名词所有格 brother's。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列句子正确的是（ ）", options: ["The dress is mine.", "The dress is my.", "It's mine dress.", "It's me dress."], answer: "A", hint: "mine 后面不接名词。", explanation: "The dress is mine.（= my dress）正确；my 后必须接名词。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— Whose shoes are these? — ____ Sarah's.", options: ["It's", "They're", "This is", "That is"], answer: "B", hint: "shoes 是复数。", explanation: "shoes 复数用 they 指代：They're Sarah's.（是莎拉的。）" },
    ],
  },
  {
    code: "G4-EN-15-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 5 My clothes",
    title: "语音：字母组合 le 发 /əl/（apple, table, people）",
    sortOrder: 0,
    summary: [
      { heading: "le 发 /əl/", body: "词尾的 le 发 /əl/（舌尖抵上齿龈）。如：apple（苹果）、table（桌子）、people（人们）、little（小的）、uncle（叔叔）。" },
      { heading: "拼写提示", body: "听到词尾 /əl/ 的音，常拼写为 le：ap-ple, ta-ble, peo-ple。注意 people 中间是 eo。" },
      { heading: "朗读练习", body: "The little uncle is at the table. He has an apple. 把 le 单词串进句子里读，词尾又轻又短。" },
    ],
    example: {
      stem: "apple、table、people 词尾的共同字母组合是什么？发什么音？",
      analysis: "三个词都以 le 结尾，le 都发 /əl/。",
      answer: "共同字母组合是 le，发 /əl/。",
    },
    prereqCodes: ["G4-EN-15-02"],
    commonErrors: [
      { cause: "拼写颠倒", detail: "把 apple 写成 \"appel\"，table 写成 \"tabel\"，词尾是 -le 不是 -el。" },
      { cause: "发音过重", detail: "把词尾 le 读成“勒”重音，/əl/ 是轻短音，重音在前面的音节。" },
    ],
    socratic: {
      keyConcepts: ["le 发 /əl/", "词尾拼写 -le", "重音在前"],
      probes: ["apple 的重音在第几个音节？词尾 le 怎么读？", "你能再举出两个以 le 结尾的单词吗？"],
      hints: ["AP-ple，重音在前，词尾轻轻带过。", "听到词尾 /əl/ 就写 le。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "apple 词尾 le 的发音是（ ）", options: ["/əl/", "/el/", "/liː/", "/leɪ/"], answer: "A", hint: "轻短的音。", explanation: "apple 词尾 le 发 /əl/。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "下列单词词尾与 table 相同的是（ ）", options: ["people", "uncle 与 people 都是，但 book 不是", "book", "name"], answer: "A", hint: "找 le 结尾的词。", explanation: "people 以 le 结尾，发 /əl/，与 table 相同。" },
      { type: "choice", stage: "practice", difficulty: 1, stem: "apple 的重音在（ ）", options: ["第一个音节", "第二个音节", "两个一样重", "词尾 le"], answer: "A", hint: "AP-ple。", explanation: "apple 读 /ˈæpl/，重音在第一个音节。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全单词：tab__（桌子）", answer: "le", hint: "词尾发 /əl/。", explanation: "table 以 le 结尾，le 发 /əl/。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列哪组单词词尾发音都相同？（ ）", options: ["apple, little, uncle", "apple, name, table", "people, kite, little", "table, cute, apple"], answer: "A", hint: "都以 le 结尾吗？", explanation: "apple、little、uncle 都以 le 结尾，词尾都发 /əl/。" },
      { type: "fill", stage: "variant", difficulty: 3, stem: "补全单词：peop__（人们）", answer: "le", hint: "词尾发 /əl/。", explanation: "people 以 le 结尾，注意中间是 eo，词尾 le 发 /əl/。" },
    ],
  },
  {
    code: "G4-EN-16-01",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 6 Shopping",
    title: "购物与评价词汇：nice, pretty, cheap, expensive, size, too",
    sortOrder: 0,
    summary: [
      { heading: "评价衣物", body: "nice（好看的）、pretty（漂亮的）、cheap（便宜的）、expensive（昂贵的）。如：This dress is pretty.（这条连衣裙很漂亮。）" },
      { heading: "尺码", body: "size（尺码）：Size 6.（6 码。）试鞋时说：Let's try size 7.（试试 7 码。）" },
      { heading: "too 的用法", body: "too + 形容词表示“太……”：They're too small.（它们太小了。）It's too expensive.（太贵了。）" },
    ],
    example: {
      stem: "用 too 表达：这双鞋太小。",
      analysis: "shoes 是复数，be 动词用 are，“太小”是 too small。",
      answer: "The shoes are too small. / They're too small.",
    },
    prereqCodes: ["G4-EN-15-01"],
    commonErrors: [
      { cause: "拼写错误", detail: "expensive 拼写较长：ex-pen-sive，不要漏写 s；pretty 双写 t。" },
      { cause: "单复数错误", detail: "The shoes is too small. 错误，shoes 是复数用 are。" },
    ],
    socratic: {
      keyConcepts: ["评价形容词", "cheap 与 expensive", "too + 形容词"],
      probes: ["cheap 和 expensive 是一对什么词？", "too small 和 very small 意思一样吗？"],
      hints: ["cheap 便宜，expensive 贵。", "too 表示“太……”（超出合适程度）。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "“便宜的”用英语说是（ ）", options: ["expensive", "cheap", "pretty", "size"], answer: "B", hint: "和“贵”相反。", explanation: "cheap 意为“便宜的”，反义词是 expensive（昂贵的）。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "The shoes ____ too small.", options: ["is", "are", "am", "be"], answer: "B", hint: "shoes 是复数。", explanation: "shoes 是复数，be 动词用 are。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— This dress is 500 yuan. — Oh, it's too ____.（太贵了。）", options: ["cheap", "expensive", "pretty", "nice"], answer: "B", hint: "价格高的感受。", explanation: "价格太高用 expensive（昂贵的）；cheap 是便宜。" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "汉译英（写单词）：尺码 ____", answer: "size", hint: "s-i-z-e。", explanation: "“尺码”是 size，如 Size 6（6 码）。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列句子正确的是（ ）", options: ["It's too expensive.", "It too expensive.", "It's to expensive.", "It's too expensive 和 It's very cheap 矛盾"], answer: "A", hint: "be 动词不能少，too 不是 to。", explanation: "It's too expensive. 正确：it + is + too + 形容词。" },
      { type: "choice", stage: "variant", difficulty: 3, stem: "店员问尺码，你穿 6 码，应回答（ ）", options: ["Size 6.", "I'm 6.", "It's 6 yuan.", "Six shoes."], answer: "A", hint: "size + 数字。", explanation: "回答尺码用 Size + 数字：Size 6." },
    ],
  },
  {
    code: "G4-EN-16-02",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 6 Shopping",
    title: "核心句型：Can I help you? / How much...?",
    sortOrder: 0,
    summary: [
      { heading: "店员用语", body: "Can I help you?（我能为您效劳吗？/ 您要点什么？）顾客回答：Yes. These shoes are nice. Can I try them on?（我能试穿吗？）" },
      { heading: "询问价格", body: "How much is this skirt?（这条裙子多少钱？）— It's 89 yuan. How much are those shoes?（那双鞋多少钱？）— They're 50 yuan. 单数用 is，复数用 are。" },
      { heading: "试穿与购买", body: "Can I try it on?（单数用 it）/ Can I try them on?（复数用 them）it's too small 就换：Can I try size 7?" },
    ],
    example: {
      stem: "— How much ____ the gloves? — They're 20 yuan.",
      analysis: "gloves（手套）是复数，be 动词用 are。",
      answer: "are",
    },
    prereqCodes: ["G4-EN-16-01"],
    commonErrors: [
      { cause: "how much 单复数", detail: "How much is the shoes? 错误，复数要用 How much are the shoes?" },
      { cause: "it/them 混淆", detail: "试鞋（shoes 复数）要说 try them on，不是 try it on。" },
    ],
    socratic: {
      keyConcepts: ["Can I help you?", "How much is/are...?", "try it/them on"],
      probes: ["问一件衬衫和问一双鞋的价格，句子有什么不同？", "shoes 是复数，试穿时用 it 还是 them？"],
      hints: ["单数 is + it，复数 are + them。", "how much 问价格。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "店员招呼顾客常说（ ）", options: ["Can I help you?", "How are you?", "What's this?", "See you."], answer: "A", hint: "“您要点什么？”", explanation: "Can I help you? 是店员招呼顾客的常用语。" },
      { type: "choice", stage: "check", difficulty: 1, stem: "— How much is this skirt? — ____ 89 yuan.", options: ["It's", "They're", "This is", "These are"], answer: "A", hint: "skirt 是单数。", explanation: "单数用 It's：It's 89 yuan." },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— How much ____ those shoes? — They're 50 yuan.", options: ["is", "are", "am", "be"], answer: "B", hint: "shoes 是复数。", explanation: "复数 shoes 用 are：How much are those shoes?" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全对话：— Can I try ____ on?（试鞋，shoes 是复数）— Sure.", answer: "them", hint: "复数用哪个代词？", explanation: "shoes 是复数，用 them：Can I try them on?" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "下列对话正确的是（ ）", options: ["— How much are the socks? — They're 10 yuan.", "— How much is the socks? — It's 10 yuan.", "— How much are the socks? — It's 10 yuan.", "— How much the socks? — 10 yuan."], answer: "A", hint: "问和答单复数一致。", explanation: "socks 复数，问 How much are，答 They're 10 yuan." },
      { type: "choice", stage: "variant", difficulty: 3, stem: "— Can I help you? — Yes. This dress is pretty. Can I try ____ on?", options: ["them", "it", "they", "its"], answer: "B", hint: "dress 是单数。", explanation: "dress 是单数，用 it：Can I try it on?" },
    ],
  },
  {
    code: "G4-EN-16-03",
    stage: STAGE, grade: GRADE, subject: SUBJECT,
    chapter: "Unit 6 Shopping",
    title: "综合运用：购物对话与四年级英语复习",
    sortOrder: 0,
    summary: [
      { heading: "完整购物对话", body: "— Can I help you? — Yes. I want a skirt. How much is it? — It's 80 yuan. — Oh, it's too expensive. How much is that one? — It's 45 yuan. — OK. I'll take it.（好的，我买了。）" },
      { heading: "句型大集合", body: "四年级核心句型：What's in/on...?（有什么）Where is/are...?（在哪里）What time is it?（几点）What's the weather like?（天气）What would you like?（想要什么）How many...?（多少）Whose...?（谁的）How much...?（多少钱）" },
      { heading: "语音大集合", body: "元音长短音：a-e /eɪ/、i-e /aɪ/、o-e /əʊ/、u-e /juː/；字母组合：er /ə/、ir/ur /ɜː/、ar /ɑː/、al /ɔː/、or /ɔː/或/ɜː/、le /əl/。" },
    ],
    example: {
      stem: "补全对话：— ____ — Yes. I want a sweater. How much is it?",
      analysis: "顾客说 Yes，说明店员先问 Can I help you?（您要点什么？）",
      answer: "Can I help you?",
    },
    prereqCodes: ["G4-EN-16-02"],
    commonErrors: [
      { cause: "疑问词混淆", detail: "how many（数量）、how much（价格/不可数量）、what time（时间）混淆，要按问题类型选疑问词。" },
      { cause: "应答不匹配", detail: "Can I help you? 是购物开场，不能用于问路；不同情景用不同句型。" },
    ],
    socratic: {
      keyConcepts: ["购物对话流程", "八个疑问句型辨析", "语音规律总复习"],
      probes: ["一次完整的购物对话有哪些步骤？", "问价格、问数量、问时间分别用什么疑问词？"],
      hints: ["how much 问价格，how many 问数量。", "把每个单元的句型串成一个小故事读一读。"],
    },
    questions: [
      { type: "choice", stage: "check", difficulty: 1, stem: "问“这条裙子多少钱”应该用（ ）", options: ["How many is this skirt?", "How much is this skirt?", "What time is it?", "Whose skirt is this?"], answer: "B", hint: "价格用 how much。", explanation: "询问价格用 How much is/are...?" },
      { type: "choice", stage: "check", difficulty: 1, stem: "问“你有多少支铅笔”应该用（ ）", options: ["How much", "How many", "What time", "What colour"], answer: "B", hint: "可数数量。", explanation: "可数名词数量用 How many + 复数名词。" },
      { type: "choice", stage: "practice", difficulty: 2, stem: "— Can I help you? — ____（顾客想买一件夹克。）", options: ["Yes. I want a jacket.", "No, it isn't.", "It's 50 yuan.", "They're pretty."], answer: "A", hint: "先答 Yes，再说想买什么。", explanation: "顾客回答 Yes. I want a jacket.（是的，我想要一件夹克。）" },
      { type: "fill", stage: "practice", difficulty: 2, stem: "补全对话：— It's 45 yuan. — OK. I'll ____ it.（好的，我买了。）", answer: "take", hint: "“买下它”用 I'll take it.", explanation: "I'll take it. 是购物时决定购买的常用语。" },
      { type: "choice", stage: "variant", difficulty: 2, stem: "把句子按购物顺序排列：①It's 80 yuan. ②Can I help you? ③How much is this sweater?（ ）", options: ["②③①", "③②①", "②①③", "①③②"], answer: "A", hint: "先招呼，再问价，再报价。", explanation: "正确顺序：店员招呼 Can I help you? → 顾客问价 How much...? → 店员报价 It's 80 yuan." },
      { type: "choice", stage: "variant", difficulty: 3, stem: "下列各组中，疑问词与问题匹配错误的是（ ）", options: ["What time — 问时间", "How many — 问价格", "Whose — 问主人", "How much — 问价格"], answer: "B", hint: "how many 问的是什么？", explanation: "How many 问可数数量，问价格用 How much。" },
    ],
  },
];
